
.ad l

.TH profile.lsf 5 "July 2021" "" ""
.ll 72

.ce 1000
\fBcshrc.lsf and profile.lsf\fR
.ce 0

.sp 2
The user environment shell files cshrc.lsf and profile.lsf set
the LSF operating environment on an LSF host.
.sp 2
The cshrc.lsf and profile.lsf files define machine-dependent
paths to LSF commands and libraries as environment variables:
.sp 2
*  The cshrc.lsf file sets the C shell (csh or tcsh) user
   environment for LSF commands and libraries.
.sp 2
*  The profile.lsf file sets and exports the Bourne shell/Korn
   shell (sh, ksh, or bash) user environment for LSF commands and
   libraries.
.sp 2
   \fBTip: \fRLSF Administrators can make sure that cshrc.lsf or
   profile.lsf are available for users to set the LSF environment
   variables correctly for the host type that is running LSF.
.SH Location

.sp 2
The cshrc.lsf and profile.lsf files are created by the lsfinstall
script during installation. After installation, they are located
in the \fBLSF_CONFDIR\fR directory (LSF_TOP/conf/).
.SH Format

.sp 2
The cshrc.lsf and profile.lsf files are conventional UNIX shell
scripts:
.sp 2
*  cshrc.lsf runs under /bin/csh
.sp 2
*  profile.lsf runs under /bin/sh
.SH What cshrc.lsf and profile.lsf do

.sp 2
The cshrc.lsf and profile.lsf files determine the binary type
(\fBBINARY_TYPE\fR) of the host and set environment variables for
the paths to the following machine-dependent LSF directories,
according to the LSF version (\fBLSF_VERSION\fR) and the location
of the top-level installation directory (\fBLSF_TOP\fR) defined
at installation:
.sp 2
*  \fBLSF_BINDIR\fR
.sp 2
*  \fBLSF_SERVERDIR\fR
.sp 2
*  \fBLSF_LIBDIR\fR
.sp 2
The cshrc.lsf and profile.lsf files also set the following user
environment variables:
.sp 2
*  \fBLSF_ENVDIR\fR
.sp 2
*  \fBLD_LIBRARY_PATH\fR
.sp 2
*  \fBPATH\fR to include the paths to the following directories:
.sp 2
   *  \fBLSF_BINDIR\fR
.sp 2
   *  \fBLSF_SERVERDIR\fR
.sp 2
*  \fBMANPATH\fR to include the path to the LSF man pages
.SH If enterprise grid orchestrator is enabledenterprise grid orchestrator is enabledis enabled

.sp 2
If enterprise grid orchestrator is enabled in the LSF cluster
(the \fBLSF_ENABLE_EGO=Y\fR and \fBLSF_EGO_ENVDIR\fR parameters
are defined in the lsf.conf file), the cshrc.lsf and profile.lsf
files set the following environment variables.
.sp 2
*  \fBEGO_BINDIR\fR
.sp 2
*  \fBEGO_CONFDIR\fR
.sp 2
*  \fBEGO_ESRVDIR\fR
.sp 2
*  \fBEGO_LIBDIR\fR
.sp 2
*  \fBEGO_LOCAL_CONFDIR\fR
.sp 2
*  \fBEGO_SERVERDIR \fR
.sp 2
*  \fBEGO_TOP\fR
.sp 2
Parent topic: Configuration files
.sp 2

.ce 1000
\fBSet the LSF environment with cshrc.lsf and profile.lsf\fR
.ce 0

.sp 2
Before you use LSF, you must use the cshrc.lsf or profile.lsf
file to set the LSF execution environment.
.sp 2
Log in to an LSF host and use one of the following shell
environment files to set your LSF environment:
.sp 2
*  In the csh or tcsh shell, run the source command:
.sp 2
   % source <LSF_TOP>/conf/cshrc.lsf
.sp 2
*  In the sh, ksh, or bash shell, run the following command:
.sp 2
   $ . <LSF_TOP>/conf/profile.lsf
.SH Making your cluster available to users with cshrc.lsf and
profile.lsf

.sp 2
\fBTip: \fRLSF administrators can make sure all LSF users include
one of these files at the end of their own .cshrc or .profile
file, or run one of these two files before you use LSF.
.SH For csh or tcsh

.sp 2
Add the cshrc.lsf file to the end of the .cshrc file for all
users:
.sp 2
*  Copy the contents of the cshrc.lsf file into the .cshrc file.
.sp 2
*  Add a line with the source command to the end of the .cshrc
   file.
.sp 2
   For example, if the \fILSF_TOP\fR directory for your cluster
   is /usr/share/lsf/conf, add the following line to the .cshrc
   file:
.sp 2
   source /usr/share/lsf/conf/cshrc.lsf
.sp 2
After you run the cshrc.lsf script, use the setenv command to see
the environment variable settings.
.sp 2
setenv
.br
 ...
.br
PATH=/usr/lsf/lsf_10/10.1/linux2.6-glibc2.3-x86/bin
.br
MANPATH=/usr/lsf/llsf_10/10.1/man 
.br
LSF_BINDIR=/usr/lsf/lsf_10/10.1/linux2.6-glibc2.3-x86/bin 
.br
LSF_SERVERDIR=/usr/lsf/lsf_10/10.1/linux2.6-glibc2.3-x86/etc 
.br
LSF_LIBDIR=/usr/lsf//10.1/linux2.6-glibc2.3-x86/lib 
.br
LD_LIBRARY_PATH=/usr/lsf/lsf_10/10.1/linux2.6-glibc2.3-x86/lib 
.br
XLSF_UIDDIR=/usr/lsf/10.1/linux2.6-glibc2.3-x86/lib/uid 
.br
LSF_ENVDIR=/usr/lsf/lsf_10/conf
.br
 ... 
.br

.sp 2
\fBNote: \fRThese variable settings are only an example. Your
system might set extra variables.
.SH For sh, ksh, or bash

.sp 2
Add profile.lsf to the end of the .profile file for all users:
.sp 2
*  Copy the contents of the profile.lsf file into the .profile
   file.
.sp 2
*  Add a line that runs the profile.lsf file to the end of the
   .profile file.
.sp 2
   For example, if the \fILSF_TOP\fR directory for your cluster
   is /usr/share/lsf/conf, add the following line to the .profile
   file:
.sp 2
   . /usr/share/lsf/conf/profile.lsf
.sp 2
After you run the profile.lsf file, use the setenv command to see
the environment variable settings.
.sp 2
setenv
.br
 ... 
.br
LD_LIBRARY_PATH=/usr/lsf/lsf_10/10.1/linux2.6-glibc2.3-x86/lib 
.br
LSF_BINDIR=/usr/lsf/lsf_10/10.1/linux2.6-glibc2.3-x86/bin 
.br
LSF_ENVDIR=/usr/lsf/lsf_10/conf 
.br
LSF_LIBDIR=/usr/lsf/lsf_10/10.1/linux2.6-glibc2.3-x86/lib 
.br
LSF_SERVERDIR=/usr/lsf/lsf_10/10.1/linux2.6-glibc2.3-x86/etc 
.br
MANPATH=/usr/lsf/lsf_10/10.1/man
.br
PATH=/usr/lsf/lsf_10/10.1/linux2.6-glibc2.3-x86/bin
.br
XLSF_UIDDIR=/usr/lsf/lsf_10/10.1/linux2.6-glibc2.3-x86/lib/uid 
.br
 ...
.br

.sp 2
\fBNote: \fRThese variable settings are only an example. Your
system might set more variables.
.SH cshrc.lsf and profile.lsf on dynamically added LSF hosts

.sp 2
Dynamically added LSF hosts that are not management candidates
are called server hosts. Each dynamic host has its own LSF binary
files, local lsf.conf file, and shell environment scripts
(cshrc.lsf and profile.lsf).
.sp 2

.ce 1000
\fBLSF environment variables set by cshrc.lsf and profile.lsf\fR
.ce 0

.sp 2
The cshrc.lsf and profile.lsf files set several LSF environment
variables.
.sp 2

.ce 1000
\fBLSF_BINDIR\fR
.ce 0

.sp 2
The \fBLSF_BINDIR\fR environment variable is set by the cshrc.lsf
and profile.lsf files.
.sp 2

.SH Syntax

.sp 2
\fRLSF_BINDIR\fR=\fIdir\fR
.SH Description

.sp 2
Directory where LSF user commands are installed.
.SH Examples

.sp 2
*  Set in csh and tcsh shells by the cshrc.lsf file:
.sp 2
   setenv LSF_BINDIR /usr/lsf/lsf_10/10.1/linux2.6-glibc2.3-x86/bin
.br

.sp 2
*  Set and exported in the sh, ksh, or bash shell by the
   profile.lsf file:
.sp 2
   LSF_BINDIR=/usr/lsf/lsf_10/10.1/linux2.6-glibc2.3-x86/bin
.br

.SH Values

.sp 2
*  In the cshrc.lsf file for the csh and tcsh shells:
.sp 2
   setenv LSF_BINDIR $LSF_TOP/$LSF_VERSION/$BINARY_TYPE/bin
.br

.sp 2
*  Set and exported in the profile.lsf file for the sh, ksh, or
   bash shell:
.sp 2
   LSF_BINDIR=$LSF_TOP/$LSF_VERSION/$BINARY_TYPE/bin
.br

.sp 2

.ce 1000
\fBLSF_ENVDIR\fR
.ce 0

.sp 2
Directory containing the lsf.conf file.
.sp 2

.SH Syntax

.sp 2
\fRLSF_ENVDIR\fR=\fIdir\fR
.SH Description

.sp 2
By default, the lsf.conf file is installed by creating a shared
copy in the \fBLSF_CONFDIR\fR directory and adding a symbolic
link from the /etc/lsf.conf directory to the shared copy. If the
\fBLSF_ENVDIR\fR variable is set, the symbolic link is installed
in the LSF_ENVDIR/lsf.conf file.
.sp 2
The lsf.conf file is a global environment configuration file for
all LSF services and applications. The LSF default installation
places the file in the \fBLSF_CONFDIR\fR directory.
.SH Examples

.sp 2
*  Set in the csh and tcsh shells by the cshrc.lsf file:
.sp 2
   setenv LSF_ENVDIR /usr/lsf/lsf_10/conf
.br

.sp 2
*  Set and exported in the sh, ksh, or bash shell by the
   profile.lsf file:
.sp 2
   LSF_ENVDIR=/usr/lsf/lsf_10/conf
.br

.SH Values

.sp 2
*  In the cshrc.lsf file for the csh and tcsh shells:
.sp 2
   setenv LSF_ENVDIR $LSF_TOP/conf
.br

.sp 2
*  Set and exported in the profile.lsf file for the sh, ksh, or
   bash shell:
.sp 2
   LSF_ENVDIR=$LSF_TOP/conf
.br

.sp 2

.ce 1000
\fBLSF_LIBDIR\fR
.ce 0

.sp 2
Directory where LSF libraries are installed.
.sp 2

.SH Syntax

.sp 2
\fRLSF_LIBDIR\fR=\fIdir\fR
.SH Description

.sp 2
Library files are shared by all hosts of the same type.
.SH Examples

.sp 2
*  Set in the csh and tcsh shells by the cshrc.lsf file:
.sp 2
   setenv LSF_LIBDIR /usr/lsf/lsf_10/10.1/linux2.6-glibc2.3-x86/lib
.br

.sp 2
*  Set and exported in the sh, ksh, or bash shell by the
   profile.lsf file:
.sp 2
   LSF_LIBDIR=/usr/lsf/lsf_10/10.1/linux2.6-glibc2.3-x86/lib
.br

.SH Values

.sp 2
*  In the cshrc.lsf file for the csh and tcsh shells:
.sp 2
   setenv LSF_LIBDIR $LSF_TOP/$LSF_VERSION/$BINARY_TYPE/lib
.br

.sp 2
*  Set and exported in the profile.lsf files for the sh, ksh, or
   bash shell:
.sp 2
   LSF_LIBDIR=$LSF_TOP/$LSF_VERSION/$BINARY_TYPE/lib
.br

.sp 2

.ce 1000
\fBLSF_SERVERDIR\fR
.ce 0

.sp 2
Directory where LSF server binary files and shell scripts are
installed.
.sp 2

.SH Syntax

.sp 2
\fRLSF_SERVERDIR\fR=\fIdir\fR
.SH Description

.sp 2
These server binary files include the lim, res, nios, sbatchd,
mbatchd, and mbschd daemons. If you use elim, eauth, eexec, esub,
or other external executable files, they are also installed in
this directory.
.SH Examples

.sp 2
*  Set in the csh and tcsh shells by cshrc.lsf files:
.sp 2
   setenv LSF_SERVERDIR /usr/lsf/lsf_10/10.1/linux2.6-glibc2.3-x86/etc
.br

.sp 2
*  Set and exported in the sh, ksh, or bash shell by the
   profile.lsf file:
.sp 2
   LSF_SERVERDIR=/usr/lsf/lsf_10/10.1/linux2.6-glibc2.3-x86/etc
.br

.SH Values

.sp 2
*  In the cshrc.lsf file for the csh and tcsh shells:
.sp 2
   setenv LSF_SERVERDIR $LSF_TOP/$LSF_VERSION/$BINARY_TYPE/etc
.br

.sp 2
*  Set and exported in the profile.lsf file for the sh, ksh, or
   bash shell:
.sp 2
   LSF_SERVERDIR=$LSF_TOP/$LSF_VERSION/$BINARY_TYPE/etc
.br

.sp 2

.ce 1000
\fBEGO environment variables set by cshrc.lsf and profile.lsf\fR
.ce 0

.sp 2
The cshrc.lsf and profile.lsf files set the following EGO
environment variables: \fBEGO_BINDIR\fR, \fBEGO_CONFDIR\fR,
\fBEGO_ESRVDIR\fR, \fBEGO_LIBDIR\fR, \fBEGO_LOCAL_CONFDIR\fR,
\fBEGO_SERVERDIR\fR, \fBEGO_TOP\fR.
.sp 2

.ce 1000
\fBEGO_BINDIR\fR
.ce 0

.sp 2
Directory where EGO user commands are installed.
.sp 2

.SH Syntax

.sp 2
\fREGO_BINDIR\fR=\fIdir\fR
.SH Description

.sp 2
The \fBEGO_BINDIR\fR environment variable sets the directory
where EGO user commands are installed.
.SH Examples

.sp 2
*  Set in the csh and tcsh shells by the cshrc.lsf file:
.sp 2
   setenv EGO_BINDIR /usr/lsf/lsf_10/10.1/linux2.6-glibc2.3-x86/bin
.br

.sp 2
*  Set and exported in the sh, ksh, or bash shell by the
   profile.lsf file:
.sp 2
   EGO_BINDIR=/usr/lsf/lsf_10/10.1/linux2.6-glibc2.3-x86/bin
.br

.SH Values

.sp 2
*  In the cshrc.lsf file for the csh and tcsh shells:
.sp 2
   setenv EGO_BINDIR $LSF_BINDIR
.br

.sp 2
*  Set and exported in the profile.lsf file for the sh, ksh, or
   bash shell:
.sp 2
   EGO_BINDIR=$LSF_BINDIR
.br

.sp 2

.ce 1000
\fBEGO_CONFDIR\fR
.ce 0

.sp 2
Directory containing the ego.conf file.
.sp 2

.SH Syntax

.sp 2
\fREGO_CONFDIR\fR=\fIdir\fR
.SH Description

.sp 2
\fBEGO_CONFDIR\fR environment variable sets the directory that
contains the ego.conf file.
.SH Examples

.sp 2
*  Set in the csh and tcsh shells by the cshrc.lsf file:
.sp 2
   setenv EGO_CONFDIR /usr/lsf/lsf_10/conf/ego/lsf1.2.3/kernel
.br

.sp 2
*  Set and exported in the sh, ksh, or bash shell by the
   profile.lsf file:
.sp 2
   EGO_CONFDIR=/usr/lsf/lsf_10/conf/ego/lsf1.2.3/kernel
.br

.SH Values

.sp 2
*  In the cshrc.lsf file for the csh and tcsh shells:
.sp 2
   setenv EGO_CONFDIR /usr/lsf/lsf_10/conf/ego/lsf1.2.3/kernel
.br

.sp 2
*  Set and exported in the profile.lsf file for the sh, ksh, or
   bash shell:
.sp 2
   EGO_CONFDIR=/usr/lsf/lsf_10/conf/ego/lsf1.2.3/kernel
.br

.sp 2

.ce 1000
\fBEGO_ESRVDIR\fR
.ce 0

.sp 2
Directory where the EGO the service controller configuration
files are stored.
.sp 2

.SH Syntax

.sp 2
\fREGO_ESRVDIR\fR=\fIdir\fR
.SH Description

.sp 2
The \fBEGO_ESRVDIR\fR environment variable sets the directory
where the EGO the service controller configuration files are
stored.
.SH Examples

.sp 2
*  Set in the csh and tcsh shells by the cshrc.lsf file:
.sp 2
   setenv EGO_ESRVDIR /usr/lsf/lsf_10/conf/ego/lsf/eservice
.br

.sp 2
*  Set and exported in the sh, ksh, or bash shell by the
   profile.lsf file:
.sp 2
   EGO_ESRVDIR=/usr/lsf/lsf_10/conf/ego/lsf/eservice
.br

.SH Values

.sp 2
*  In the cshrc.lsf file for the csh and tcsh shells:
.sp 2
   setenv EGO_ESRVDIR /usr/lsf/lsf_10/conf/ego/lsf/eservice
.br

.sp 2
*  Set and exported in the profile.lsf file for the sh, ksh, or
   bash shell:
.sp 2
   EGO_ESRVDIR=/usr/lsf/lsf_10/conf/ego/lsf/eservice
.br

.sp 2

.ce 1000
\fBEGO_LIBDIR\fR
.ce 0

.sp 2
Directory where EGO libraries are installed.
.sp 2

.SH Syntax

.sp 2
\fREGO_LIBDIR\fR=\fIdir\fR
.SH Description

.sp 2
The \fBEGO_LIBDIR\fR environment variable sets the directory
where EGO libraries are installed. Library files are shared by
all hosts of the same type.
.SH Examples

.sp 2
*  Set in the csh and tcsh shells by the cshrc.lsf file:
.sp 2
   setenv EGO_LIBDIR /usr/lsf/lsf_10/10.1/linux2.6-glibc2.3-x86/lib
.br

.sp 2
*  Set and exported in the sh, ksh, or bash shell by the
   profile.lsf file:
.sp 2
   EGO_LIBDIR=/usr/lsf/lsf_10/10.1/linux2.6-glibc2.3-x86/lib
.br

.SH Values

.sp 2
*  In the cshrc.lsf file for the csh and tcsh shells:
.sp 2
   setenv EGO_LIBDIR $LSF_LIBDIR
.br

.sp 2
*  Set and exported in the profile.lsf file for the sh, ksh, or
   bash shell:
.sp 2
   EGO_LIBDIR=$LSF_LIBDIR
.br

.sp 2

.ce 1000
\fBEGO_LOCAL_CONFDIR\fR
.ce 0

.sp 2
The local EGO configuration directory that contains the ego.conf
file.
.sp 2

.SH Syntax

.sp 2
\fREGO_LOCAL_CONFDIR\fR=\fIdir\fR
.SH Description

.sp 2
The \fBEGO_LOCAL_CONFDIR\fR environment variable sets the local
EGO configuration directory that contains the ego.conf file.
.SH Examples

.sp 2
*  Set in csh and tcsh by cshrc.lsf:
.sp 2
   setenv EGO_LOCAL_CONFDIR /usr/lsf/llsf_10/conf/ego/lsf1.2.3/kernel
.br

.sp 2
*  Set and exported in sh, ksh, or bash by profile.lsf:
.sp 2
   EGO_LOCAL_CONFDIR=/usr/lsf/lsf_10/conf/ego/lsf1.2.3/kernel
.br

.SH Values

.sp 2
*  In cshrc.lsf for csh and tcsh:
.sp 2
   setenv EGO_LOCAL_CONFDIR /usr/lsf/lsf_10/conf/ego/lsf1.2.3/kernel
.br

.sp 2
*  Set and exported in profile.lsf for sh, ksh, or bash:
.sp 2
   EGO_LOCAL_CONFDIR=/usr/lsf/lsf_10/conf/ego/lsf1.2.3/kernel
.br

.sp 2

.ce 1000
\fBEGO_SERVERDIR\fR
.ce 0

.sp 2
Directory where EGO server binary files and shell scripts are
installed.
.sp 2

.SH Syntax

.sp 2
\fREGO_SERVERDIR\fR=\fIdir\fR
.SH Description

.sp 2
The server binary files in the \fBEGO_SERVERDIR\fR directory
include vemkd, pem, egosc, and shell scripts for EGO startup and
shutdown.
.SH Examples

.sp 2
*  Set in csh and tcsh by cshrc.lsf:
.sp 2
   setenv EGO_SERVERDIR /usr/lsf/llsf_10/10.1/linux2.6-glibc2.3-x86/etc
.br

.sp 2
*  Set and exported in sh, ksh, or bash by profile.lsf:
.sp 2
   EGO_SERVERDIR=/usr/lsf/lsf_10/10.1/linux2.6-glibc2.3-x86/etc
.br

.SH Values

.sp 2
*  In cshrc.lsf for csh and tcsh:
.sp 2
   setenv EGO_SERVERDIR $LSF_SERVERDIR
.br

.sp 2
*  Set and exported in profile.lsf for sh, ksh, or bash:
.sp 2
   EGO_SERVERDIR=$LSF_SERVERDIR
.br

.sp 2

.ce 1000
\fBEGO_TOP\fR
.ce 0

.sp 2
The top-level installation directory for EGO.
.sp 2

.SH Syntax

.sp 2
\fREGO_TOP\fR=\fIdir\fR
.SH 

.sp 2
The path to the \fBEGO_TOP\fR directory must be shared and
accessible to all hosts in the cluster. Equivalent to the
\fBLSF_TOP\fR directory.
.SH Examples

.sp 2
*  Set in csh and tcsh by cshrc.lsf:
.sp 2
   setenv EGO_TOP /usr/lsf/lsf_10
.br

.sp 2
*  Set and exported in sh, ksh, or bash by profile.lsf:
.sp 2
   EGO_TOP=/usr/lsf/lsf_10
.br

.SH Values

.sp 2
*  In cshrc.lsf for csh and tcsh:
.sp 2
   setenv EGO_TOP /usr/lsf/lsf_10
.br

.sp 2
*  Set and exported in profile.lsf for sh, ksh, or bash:
.sp 2
   EGO_TOP=/usr/lsf/lsf_10
.br
