
.ad l

.TH blhosts 1 "July 2021" "" ""
.ll 72

.ce 1000
\fBblhosts\fR
.ce 0

.sp 2
Displays the names of all the hosts that are running the LSF
License Scheduler daemon (\fRbld\fR).
.sp 2

.SH Synopsis

.sp 2
\fBblhosts\fR [\fB-h\fR | \fB-V\fR]
.SH Description

.sp 2
The list includes the LSF License Scheduler management host and
all the candidate LSF License Scheduler hosts running the bld
daemon.
.SH Options

.sp 2
\fB-h\fR
.br
         Prints command usage to stderr and exits.
.sp 2
\fB-V\fR
.br
         Prints release version to stderr and exits.
.SH Output

.sp 2
Prints the names of all the hosts that are running the LSF
License Scheduler bld daemon.
.sp 2
For example, the following sample output shows the LSF License
Scheduler management host and two candidate LSF License Scheduler
hosts running the bld daemon:
.sp 2
bld is running on:
.br
management host: host1.domain1.com
.br
server host: host2.domain1 host3.domain1
.br

.SH See also

.sp 2
blinfo, blstat, bladmin