
.ad l

.TH blkill 1 "July 2021" "" ""
.ll 72

.ce 1000
\fBblkill\fR
.ce 0

.sp 2
Terminates an interactive (taskman) LSF License Scheduler task.
.sp 2

.SH Synopsis

.sp 2
\fBblkill\fR [\fB-t\fR seconds] task_ID
.sp 2
\fBblkill\fR [\fB-h\fR | \fB-V\fR]
.SH Description

.sp 2
Terminates a running or waiting interactive task in LSF License
Scheduler
.sp 2
Users can kill their own tasks. You must be a LSF License
Scheduler administrator to terminate another user’s task.
.sp 2
By default, the blkill command notifies the user and waits 60
seconds before it kills the task.
.SH Options

.sp 2
\fB\fItask_ID\fB\fR
.br
         Task ID of the task you want to kill.
.sp 2
\fB-t \fIseconds\fB\fR
.br
         Specify how many seconds to delay before the blkill
         command kills the task. A value of \fR0\fR means to kill
         the task immediately (do not give the user any time to
         save work).
.sp 2
\fB-h\fR
.br
         Prints command usage to stderr and exits.
.sp 2
\fB-V\fR
.br
         Prints LSF License Scheduler release version to stderr
         and exits.