
.ad l

.TH blstat 1 "July 2021" "" ""
.ll 72

.ce 1000
\fBblstat\fR
.ce 0

.sp 2
Displays dynamic license information.
.sp 2

.SH Synopsis

.sp 2
\fBblstat\fR [\fB-s\fR] [\fB-S\fR] [\fB-D\fR service_domain_name
| \fB"\fRservice_domain_name ...\fB"\fR] [\fB-P\fR][\fB-t\fR
token_name | \fB"\fRtoken_name ...\fB"\fR] [\fB-o\fR \fBalpha\fR
| \fBtotal\fR | \fBavail\fR] [\fB-g "\fRfeature_group ...\fB"\fR]
[\fB-slots\fR]
.sp 2
\fBblstat\fR [\fB-a\fR] [\fB-c\fR token_name] [\fB-G\fR]
[\fB-Lp\fR ls_project_name | \fB"\fRls_project_name ...\fB"\fR]
.sp 2
\fBblstat\fR [\fB-D\fR service_domain_name |
\fB"\fRservice_domain_name ...\fB"\fR] [\fB-t\fR token_name |
\fB"\fRtoken_name ...\fB"\fR] [\fB-f
"\fRfield_name[\fB:\fR[\fB-\fR][output_width]] ...
[\fBdelimiter=\(aq\fRcharacter\fB\(aq\fR]\fB"\fR ] [\fB-a\fR]
[\fB-alloc\fR] [\fB-cname\fR] [\fB-noheader\fR] [\fB-x\fR]
[\fB-X\fR] [\fB-R "\fRres_req\fB"\fR] [host_name ... | host_group
 ... | compute_unit ...]
.sp 2
\fBblstat\fR [\fB-Lp\fR ls_project_name | \fB"\fRls_project_name
 ...\fB"\fR] [\fB-f "\fRfield_name[\fB:\fR[\fB-\fR][output_width]]
 ... [\fBdelimiter=\(aq\fRcharacter\fB\(aq\fR]\fB"\fR ] [\fB-a\fR]
[\fB-alloc\fR] [\fB-cname\fR] [\fB-noheader\fR] [\fB-x\fR]
[\fB-X\fR] [\fB-R "\fRres_req\fB"\fR] [host_name ... | host_group
 ... | compute_unit ...]
.sp 2
\fBblstat\fR [\fB-h\fR | \fB-V\fR]
.SH Description

.sp 2
Displays license usage statistics for LSF License Scheduler.
.sp 2
By default, shows information about all licenses and all
clusters.
.SH Options for cluster mode and project mode

.sp 2
\fB-S\fR
.br
         Displays information on the license servers that are
         associated with license features.
.sp 2
\fB-s\fR
.br
         Displays license usage of the LSF and non-LSF workloads.
         Workload distributions are defined by the
         \fBWORKLOAD_DISTRIBUTION\fR parameter in the
         lsf.licensescheduler file. The blstat command marks any
         distribution policy violations with an asterisk
         (\fR*\fR) at the beginning of the line.
.sp 2
\fB-D \fIservice_domain_name\fB | "\fIservice_domain_name\fB
 ..."\fR
.br
         Shows information only about specified service domains.
         Use spaces to separate multiple names, and enclose names
         in quotation marks.
.sp 2
\fB-f \fIoutput_format_string\fB\fR
.br
         Sets the customized output format.
.sp 2
         *  Specify which blstat fields (or aliases instead of
            the full field names), in which order, and with what
            width to display.
.sp 2
         *  Specify only the blstat field name or alias to set
            its output to unlimited width and left justification.
.sp 2
         *  Specify the colon (\fR:\fR) without a width to set
            the output width to the recommended width for that
            field.
.sp 2
         *  Specify the colon (\fR:\fR) with a width to set the
            maximum number of characters to display for the
            field. When the value exceeds this width, blstat
            truncates the output.
.sp 2
         *  Specify a hyphen (\fR-\fR) to set right justification
            when blstat displays the output for the specific
            field. If not specified, the default is to set left
            justification.
.sp 2
         *  Use \fRdelimiter=\fR to set the delimiting character
            to display between different headers and fields. This
            delimiter must be a single character. By default, the
            delimiter is a space.
.sp 2
         Output customization applies only to the blstat command
         with no options, and to output for blstat with the
         following options: -Lp, -D, -t. The -f option does not
         work with any other blstat option.
.sp 2
         The following are the field names used to specify the
         blstat fields to display, recommended width, aliases you
         can use instead of field names, the applicable LSF
         License Scheduler modes, and a brief description of the
         field:
.sp 2
         \fBTable 1. Output fields for blstat\fR
.sp 2
+--------------------------------+-------+------------------+---+
| Field name                     | Width | Alias            | M |
|                                |       |                  | o |
|                                |       |                  | d |
|                                |       |                  | e |
+--------------------------------+-------+------------------+---+
| service_domain_name            | 19    | sd_name          | a |
|--------------------------------|-------|------------------| l |
| service_domain_others          | 9     | sd_others        |   |
|                                |       |                  |   |
|                                |       |                  | l |
| service_domain_lsf_total       | 12    | sd_lsf_total     |   |
+--------------------------------+-------+------------------+---+
| service_domain_alloc           | 8     | sd_alloc         | c |
|--------------------------------|-------|------------------| l |
| service_domain_use             | 7     | sd_use           | u |
|                                |       |                  | s |
|                                |       |                  | t |
|                                |       |                  | e |
|                                |       |                  | r |
|                                |       |                  | m |
|                                |       |                  | o |
|                                |       |                  | d |
|                                |       |                  | e |
+--------------------------------+-------+------------------+---+
| service_domain_inuse           | 8     | sd_inuse         | p |
|--------------------------------|-------|------------------| r |
| service_domain_reserve         | 7     | sd_rsv           | o |
|--------------------------------|-------|------------------| j |
| service_domain_free            | 7     | sd_free          | e |
|--------------------------------|-------|------------------| c |
| project_name                   | 15    | proj_name        | t |
|--------------------------------|-------|------------------| a |
| project_share                  | 7     | proj_share       | n |
|--------------------------------|-------|------------------| d |
| project_own                    | 7     | proj_own         | f |
|--------------------------------|-------|------------------| a |
| project_inuse                  | 7     | proj_inuse       | s |
|--------------------------------|-------|------------------| t |
| project_reserve                | 7     | proj_rsv         |   |
|                                |       |                  |   |
|                                |       |                  | d |
|                                |       |                  | i |
|                                |       |                  | s |
|                                |       |                  | p |
|                                |       |                  | a |
|                                |       |                  | t |
|                                |       |                  | c |
|                                |       |                  | h |
|                                |       |                  | m |
|                                |       |                  | o |
|                                |       |                  | d |
|                                |       |                  | e |
| project_free                   | 7     | proj_free        |   |
|--------------------------------|-------|------------------|   |
| project_demand                 | 8     | proj_demand      |   |
|--------------------------------|-------|------------------|   |
| project_limit                  | 7     | proj_limit       |   |
|--------------------------------|-------|------------------|   |
| project_non_share              | 11    | proj_non_share   |   |
+--------------------------------+-------+------------------+---+
| cluster_name                   | 15    | cl_name          | a |
|                                |       |                  | l |
|                                |       |                  | l |
+--------------------------------+-------+------------------+---+
| cluster_share                  | 7     | cl_share         | c |
|                                |       |                  | l |
|                                |       |                  | u |
|                                |       |                  | s |
|                                |       |                  | t |
|                                |       |                  | e |
|                                |       |                  | r |
|                                |       |                  | m |
|                                |       |                  | o |
|                                |       |                  | d |
|                                |       |                  | e |
+--------------------------------+-------+------------------+---+
| cluster_alloc                  | 7     | cl_alloc         | c |
|--------------------------------|-------|------------------| l |
| cluster_target                 | 8     | cl_target        | u |
|                                |       |                  | s |
|                                |       |                  | t |
|                                |       |                  | e |
|                                |       |                  | r |
|                                |       |                  | a |
|                                |       |                  | n |
|                                |       |                  | d |
|                                |       |                  | f |
|                                |       |                  | a |
|                                |       |                  | s |
|                                |       |                  | t |
|                                |       |                  | d |
|                                |       |                  | i |
|                                |       |                  | s |
|                                |       |                  | p |
|                                |       |                  | a |
|                                |       |                  | t |
|                                |       |                  | c |
|                                |       |                  | h |
|                                |       |                  | m |
|                                |       |                  | o |
|                                |       |                  | d |
|                                |       |                  | e |
+--------------------------------+-------+------------------+---+
| cluster_inuse                  | 7     | cl_inuse         | a |
|--------------------------------|-------|------------------| l |
| cluster_reserve                | 7     | cl_rsv           |   |
|                                |       |                  |   |
|                                |       |                  | l |
| cluster_free                   | 7     | cl_free          |   |
+--------------------------------+-------+------------------+---+
| cluster_over                   | 7     | cl_over          | c |
|                                |       |                  | l |
|                                |       |                  | u |
|                                |       |                  | s |
|                                |       |                  | t |
|                                |       |                  | e |
|                                |       |                  | r |
|                                |       |                  | a |
|                                |       |                  | n |
|                                |       |                  | d |
|                                |       |                  | f |
|                                |       |                  | a |
|                                |       |                  | s |
|                                |       |                  | t |
|                                |       |                  | d |
|                                |       |                  | i |
|                                |       |                  | s |
|                                |       |                  | p |
|                                |       |                  | a |
|                                |       |                  | t |
|                                |       |                  | c |
|                                |       |                  | h |
|                                |       |                  | m |
|                                |       |                  | o |
|                                |       |                  | d |
|                                |       |                  | e |
+--------------------------------+-------+------------------+---+
| cluster_demand                 | 8     | cl_demand        | a |
|                                |       |                  | l |
|                                |       |                  | l |
+--------------------------------+-------+------------------+---+
| cluster_peak                   | 7     | cl_peak          | c |
|--------------------------------|-------|------------------| l |
| cluster_buffer                 | 8     | cl_buff          | u |
|                                |       |                  | s |
|                                |       |                  | t |
|                                |       |                  | e |
|                                |       |                  | r |
|                                |       |                  | m |
|                                |       |                  | o |
|                                |       |                  | d |
|                                |       |                  | e |
+--------------------------------+-------+------------------+---+
| cluster_acum_use               | 10    | cl_acum_use      | p |
|--------------------------------|-------|------------------| r |
| cluster_scaled_acum            | 13    | cl_scaled_acum   |   |
|                                |       |                  |   |
|                                |       |                  | o |
|                                |       |                  | j |
|                                |       |                  | e |
|                                |       |                  | c |
|                                |       |                  | t |
|                                |       |                  | m |
|                                |       |                  | o |
|                                |       |                  | d |
|                                |       |                  | e |
| cluster_avail                  | 7     | cl_avail         |   |
+--------------------------------+-------+------------------+---+
| feature_name                   | 18    | feat_name        | a |
|--------------------------------|-------|------------------| l |
| feature_mode                   | 20    | feat_mode        |   |
|                                |       |                  |   |
|                                |       |                  | l |
| feature_lm_license_name        | 17    | feat_lm_lic_name |   |
+--------------------------------+-------+------------------+---+
.sp 2
         \fBNote: \fRField names and aliases are not
         case-sensitive. Valid values for the output width are
         any positive integer 1 - 4096.
.sp 2
\fB-g \fIfeature_group\fB ...\fR
.br
         When \fBFEATURE_GROUP\fR is configured for a group of
         license features in the lsf.licensescheduler file, shows
         information about features that are configured in the
         \fBFEATURE_LIST\fR parameter for specified feature
         groups. You can specify more than one feature group.
.sp 2
         When you specify feature names with the -t option,
         features in the \fBFEATURE_LIST\fR value that is defined
         by the -t option and feature groups are both displayed.
.sp 2
         Feature groups that are listed but not defined in the
         lsf.licensescheduler file are ignored.
.sp 2
\fB-slots\fR
.br
         Displays how many slots are currently used by LSF
         License Scheduler jobs (\fRCurrent job slots in use\fR)
         and the peak number of slots in use (\fRPeak job slots
         used\fR.
.sp 2
\fB-o alpha | total | avail\fR
.br
         Sorts license feature information alphabetically by
         total licenses, or by available licenses.
.sp 2
         \fBalpha\fR
.br
                  Features are listed in descending alphabetical
                  order.
.sp 2
         \fBtotal\fR
.br
                  Features are sorted by the descending order of
                  the sum of licenses that are allocated to LSF
                  workload from all the service domains that are
                  configured to supply licenses to the feature.
                  Licenses that are borrowed by non-LSF workload
                  are not included in this amount.
.sp 2
         \fBavail\fR
.br
                  Features are sorted by descending order of
                  licenses available, including free tokens.
.sp 2
\fB-P\fR
.br
         Displays percentage values for \fRINUSE\fR and
         \fRRESERVE\fR. The percentage value represents the
         number of used and reserved tokens that the project has,
         compared to total number of licenses.
.sp 2
\fB-t \fItoken_name\fB | "\fItoken_name\fB ..."\fR
.br
         Shows only information about specified license tokens.
         Use spaces to separate multiple names, and enclose the
         names in quotation marks.
.sp 2
\fB-h\fR
.br
         Prints command usage to stderr and exits.
.sp 2
\fB-V\fR
.br
         Prints the release version to stderr and exits.
.SH Options for project mode only

.sp 2
\fB-a\fR
.br
         Displays each project group’s accumulated value of
         licenses. The license token dispatch order is based on
         the sort order, which is based on the scaled accumulate
         value of each project. The lower the value, the sooner
         the license token is dispatched to that project.
.sp 2
\fB-c \fItoken_name\fB\fR
.br
         Displays cross cluster information for tokens.
.sp 2
         In project mode, the information is sorted by the value
         of the \fBSCALED_ACUM\fR parameter. The first cluster
         that is listed receives tokens first.
.sp 2
         Information that is displayed includes token usage,
         reserved tokens, free tokens, demand for tokens,
         accumulated value of tokens, and scaled accumulate value
         of tokens in each cluster.
.sp 2
         For fast dispatch project mode, also displays the actual
         and ideal number of tokens that are allocated to the
         cluster:
.sp 2
         \fB\fRTARGET\fB\fR
.br
                  The ideal number of licenses that are allocated
                  to the cluster.
.sp 2
         \fB\fROVER\fB\fR
.br
                  The number of licenses that are checked out by
                  \fRRUN\fR jobs in the cluster under the license
                  projects in excess of the \fRrusage\fR value.
.sp 2
         \fB\fRFREE\fB\fR
.br
                  The number of license that is allocated to the
                  cluster but not used.
.sp 2
         \fB\fRDEMAND\fB\fR
.br
                  The number of tokens that are required by the
                  cluster under the license project.
.sp 2
\fB-G\fR
.br
         Displays dynamic hierarchical license information.
.sp 2
         The blstat -G command also works with the -t option to
         display only hierarchical information for the specified
         feature names.
.sp 2
\fB-Lp \fIls_project_name\fB | "\fIls_project_name\fB ..."\fR
.br
         Shows project description for specified non-hierarchical
         projects. Use spaces to separate multiple names and
         enclose names in quotation marks.
.sp 2
         If project group paths are enabled
         (\fBPROJECT_GROUP_PATH=Y\fR parameter in the
         lsf.licensescheduler file), the blstat -Lp command
         displays the license projects that are associated with
         the specified project for all features. The blstat -Lp
         -t command displays the associated license projects for
         the specified feature. If the parameter is disabled,
         only the specified project is displayed.
.SH Output

.sp 2
Information is organized first by license feature, then by
service domain. For each combination of license and service
domain, LSF License Scheduler displays a line of summary
information followed by rows of license project or cluster
information.
.sp 2
In each group of statistics, numbers and percentages refer only
to licenses of the specified license feature that can be checked
out from FlexNet license server hosts in the specified service
domain.
.SH Cluster mode summary output

.sp 2
\fBFEATURE\fR
.br
         The license name. This name appears only once for each
         feature.
.sp 2
\fBSERVICE_DOMAIN\fR
.br
         The name of the service domain that provided the
         license.
.sp 2
\fBTOTAL_TOKENS\fR
.br
         The number of licenses from this service domain that is
         reserved for LSF License Scheduler jobs.
.sp 2
\fBTOTAL_ALLOC\fR
.br
         The number of licenses from this service domain that are
         allocated to clusters by LSF License Scheduler.
.sp 2
         In most cases \fBTOTAL_ALLOC\fR is equal to
         \fBTOTAL_USE\fR, however, when there are licenses
         counted under \fBOTHERS\fR or when tokens are reclaimed,
         \fBTOTAL_ALLOC\fR might be less than \fBTOTAL_TOKENS\fR.
.sp 2
\fBTOTAL_USE\fR
.br
         The number of licenses in use by LSF License Scheduler
         projects, which are determined by totaling all
         \fBINUSE\fR, \fBRESERVE\fR, and \fBOVER\fR values.
.sp 2
\fBOTHERS\fR
.br
         The number of licenses that are checked out by
         applications outside of LSF License Scheduler.
.SH Cluster output for cluster mode

.sp 2
For each cluster that is configured to use the license, the
\fRblstat\fR command displays the following information.
.sp 2
\fBCLUSTER\fR
.br
         The cluster name.
.sp 2
\fBSHARE\fR
.br
         The percentage of licenses that are assigned to the
         license project by the LSF License Scheduler
         administrator. The share determines how many licenses
         the project is entitled to when projects compete for
         licenses. This information is static, and for a LAN
         service domain is always 100%.
.sp 2
         The percentage is calculated to one decimal place by
         using the share assignment in the lsf.licensescheduler
         file.
.sp 2
\fBALLOC\fR
.br
         The number of licenses that are currently allocated to
         the cluster by the bld daemon.
.sp 2
\fBTARGET\fR
.br
         The ideal number of licenses that are allocated to the
         cluster. Normally, this amount is the same as the
         \fRALLOC\fR field, but the values might temporarily be
         different. For example, when a license is reclaimed,
         where one cluster is using more than its allocation,
         another cluster is prevented from getting its ideal
         amount.
.sp 2
\fBINUSE\fR
.br
         The number of licenses that are checked out by jobs in
         the cluster.
.sp 2
\fBRESERVE\fR
.br
         The number of licenses that are reserved in the service
         domain for jobs that are running in the cluster. This
         value is the difference between the job \fRrusage\fR and
         the number of checked out licenses attributed to the job
         by LSF License Scheduler.
.sp 2
         If the same license is available from both LAN and WAN
         service domains in cluster mode, LSF License Scheduler
         expects jobs to try to obtain the license from the LAN
         first. The administrator must make sure that
         applications behave in this manner, by using the FlexNet
         environment variables and \fBLM_LICENSE_FILE\fR.
.sp 2
\fBOVER\fR
.br
         The amount of license check-outs exceeding \fRrusage\fR,
         summed over all jobs.
.sp 2
\fBPEAK\fR
.br
         By default, the maximum of
         \fR\fBINUSE\fR+\fBRESERVE\fR+\fBOVER\fR\fR observed over
         the past 5 minutes. The observation period is set by the
         \fBPEAK_INUSE_PERIOD\fR parameter in either the
         \fBParameters\fR or \fBFeature\fR section.
.sp 2
         \fBPEAK\fR is used in scheduling to estimate the
         cluster’s capacity to use licenses in this service
         domain.
.sp 2
\fBBUFFER\fR
.br
         The optional allocation buffer that is configured in the
         \fBALLOC_BUFFER\fR parameter of the \fBFeature\fR
         section for WAN service domains. When defined, dynamic
         license token allocation is enabled.
.sp 2
\fBFREE\fR
.br
         The number of licenses the cluster has free. The license
         tokens are allocated to the license project by LSF
         License Scheduler, but the licenses are not reserved and
         are not yet checked out from the FlexNet license
         manager.
.sp 2
\fBDEMAND\fR
.br
         Numeric value that indicates the number of tokens that
         are required by each cluster.
.SH Project mode summary output

.sp 2
\fBFEATURE\fR
.br
         The license name. This name appears only once for each
         feature.
.sp 2
\fBSERVICE_DOMAIN\fR
.br
         The name of the service domain that provided the
         license.
.sp 2
\fBTOTAL_INUSE\fR
.br
         The number of licenses in use by LSF License Scheduler
         projects. Represents licenses in use that are checked
         out from the FlexNet license manager.
.sp 2
\fBTOTAL_RESERVE\fR
.br
         The number of licenses that are reserved for LSF License
         Scheduler projects. Represents licenses that are
         reserved and are not yet checked out from the FlexNet
         license manager.
.sp 2
\fBTOTAL_FREE\fR
.br
         The number of free licenses that are available to LSF
         License Scheduler projects. Represents licenses that are
         not reserved or in use.
.sp 2
\fBOTHERS\fR
.br
         The number of licenses that are checked out by users who
         are not submitting their jobs to LSF License Scheduler
         projects.
.sp 2
         By default, in project mode these licenses are not being
         managed by LSF License Scheduler policies.
.sp 2
         (Project mode only) To enforce license distribution
         policies for these license features, configure the
         \fRENABLE_DYNAMIC_RUSAGE=Y\fR parameter in the
         \fBFeature\fR section for those features in the
         lsf.licensescheduler file.
.SH Workload output for both modes

.sp 2
\fBLSF_USE\fR
.br
         The total number of licenses in use by LSF License
         Scheduler projects in the LSF workload.
.sp 2
\fBLSF_DESERVE\fR
.br
         The total number of licenses that are assigned to LSF
         License Scheduler projects in the LSF workload.
.sp 2
\fBLSF_FREE\fR
.br
         The total number of free licenses available to LSF
         License Scheduler projects in the LSF workload.
.sp 2
\fBNON_LSF_USE\fR
.br
         The total number of licenses in use by projects in the
         non-LSF workload.
.sp 2
\fBNON_LSF_DESERVE\fR
.br
         The total number of licenses that are assigned to
         projects in the non-LSF workload.
.sp 2
\fBNON_LSF_FREE\fR
.br
         The total number of free licenses available to projects
         in the non-LSF workload.
.SH Project output for project mode

.sp 2
For each project that is configured to use the license, the
\fRblstat\fR command displays the following information.
.sp 2
\fBPROJECT\fR
.br
         The LSF License Scheduler project name.
.sp 2
\fBSHARE\fR
.br
         The percentage of licenses that are assigned to the
         license project by the LSF License Scheduler
         administrator. The share value determines how many
         licenses the project is entitled to when projects
         compete for licenses. This information is static.
.sp 2
         The percentage is calculated to one decimal place by
         using the share assignment in the lsf.licensescheduler
         file.
.sp 2
\fBLIMITS\fR
.br
         The maximum number of licenses that the hierarchical
         project group member project can use at any one time.
.sp 2
\fBOWN\fR
.br
         Numeric value that indicates the number of tokens that
         are owned by each project.
.sp 2
\fBINUSE\fR
.br
         The number of licenses in use by the license project.
         Licenses in use are checked out from the FlexNet license
         manager.
.sp 2
\fBRESERVE\fR
.br
         The number of licenses that are reserved for the license
         project. The corresponding job is running, but its
         license is not yet checked out from the FlexNet license
         manager.
.sp 2
\fBFREE\fR
.br
         The number of licenses the license project has free. The
         license tokens are allocated to the license project by
         LSF License Scheduler, but the licenses are not reserved
         and are not yet checked out from the FlexNet license
         manager.
.sp 2
\fBDEMAND\fR
.br
         Numeric value that indicates the number of tokens that
         are required by each project.
.sp 2
\fBNON_SHARED\fR
.br
         The number of non-shared licenses that belong to the
         license project. The license tokens that are allocated
         to non-shared distribution are scheduled before the
         tokens allocated to shared distribution.
.sp 2
\fBDESCRIPTION\fR
.br
         Description of the project.
.sp 2
\fBACUM_USE\fR
.br
         The number of tokens that are accumulated by each
         consumer at run time. It is the number of licenses that
         are assigned to a consumer for a specific feature.
.sp 2
\fBSCALED_ACUM\fR
.br
         The number of tokens that are accumulated by each
         consumer at run time, divided by the \fRSHARE\fR value.
         LSF License Scheduler uses this value to schedule the
         tokens for each project.
.SH Cross cluster token output for project mode

.sp 2
For each project that is configured to use the license, the
\fRblstat -c\fR command displays the following information.
.sp 2
\fBPROJECT\fR
.br
         The LSF License Scheduler project name.
.sp 2
\fBCLUSTER\fR
.br
         The name of a cluster that uses the project.
.sp 2
\fBINUSE\fR
.br
         The number of licenses in use by the license project.
         Licenses in use are checked out from the FlexNet license
         manager.
.sp 2
\fBRESERVE\fR
.br
         The number of licenses that are reserved for the license
         project. The corresponding job is running, but its
         license is not yet checked out from the FlexNet license
         manager.
.sp 2
\fBFREE\fR
.br
         The number of licenses the license project has free. The
         license tokens are allocated to the license project by
         LSF License Scheduler, but the licenses are not reserved
         and are not yet checked out from the FlexNet license
         manager.
.sp 2
\fBNEED\fR
.br
         The total number of tokens that are required by pending
         jobs (\fRrusage\fR).
.sp 2
\fBACUM_USE\fR
.br
         The number of tokens that are accumulated by each
         consumer at run time. It is the number of licenses that
         are assigned to a consumer for a specific feature.
.sp 2
\fBSCALED_ACUM\fR
.br
         The number of tokens that are accumulated by each
         consumer at run time, divided by the \fRSHARE\fR value.
         LSF License Scheduler uses this value to schedule the
         tokens for each project.
.SH Cross cluster token output for fast dispatch project mode

.sp 2
For each project in fast dispatch project mode that is configured
to use the license, \fRblstat -c\fR displays the following
information.
.sp 2
\fBPROJECT\fR
.br
         The LSF License Scheduler project name.
.sp 2
\fBCLUSTER\fR
.br
         The name of a cluster that uses the project.
.sp 2
\fBALLOC\fR
.br
         The actual number of licenses that are currently
         allocated to the cluster. It is possible that the sum of
         licenses in the \fRINUSE\fR, \fRRESERVE\fR, and
         \fROVER\fR fields are larger than the \fRALLOC\fR field.
         In this case, the number of tokens that the cluster
         occupies will eventually decrease towards the
         \fRALLOC\fR value after the job finishes.
.sp 2
         The percentage is calculated to one decimal place by
         using the share assignment in the lsf.licensescheduler
         file.
.sp 2
\fBTARGET\fR
.br
         The ideal number of licenses that are allocated to the
         cluster. Normally, this amount is the same as the
         \fRALLOC\fR field, but the values might temporarily be
         different. For example, a license is reclaimed, where
         one cluster is using more than its allocation, which
         prevents another cluster from getting its ideal amount.
.sp 2
\fBINUSE\fR
.br
         The number of licenses in use by the cluster under the
         license project. Licenses in use are checked out from
         the FlexNet license manager.
.sp 2
\fBRESERVE\fR
.br
         The number of licenses that are reserved by jobs in the
         cluster under the license project. The corresponding job
         is running, but its license is not yet checked out from
         the FlexNet license manager. The \fRINUSE\fR and
         \fRRESERVE\fR fields add up to the \fRrusage\fR of
         \fRRUN\fR jobs in the cluster.
.sp 2
\fBOVER\fR
.br
         The number of licenses that are checked out by \fRRUN\fR
         jobs in the cluster under the license project in excess
         of the \fRrusage\fR value.
.sp 2
\fBFREE\fR
.br
         The number of licenses that the cluster under the
         license project has free. The license tokens are
         allocated to the license project by LSF License
         Scheduler, but the licenses are not reserved and are not
         yet checked out from the FlexNet license manager.
.sp 2
\fBDEMAND\fR
.br
         Numeric value reported from the cluster, which indicates
         the number of tokens that are required by the cluster
         under the license project.
.SH Project group output for project mode

.sp 2
\fBSHARE_INFO_FOR\fR
.br
         The root member and name of the hierarchical project
         group. The project information that is displayed after
         this title shows the information specific to this
         particular project group. If this root member is itself
         a member of another project group, the relationship is
         displayed as follows:
.sp 2
         \fR/\fIroot_name\fR/\fImember_name\fR/...\fR
.sp 2
\fBPROJECT/GROUP\fR
.br
         The members of the hierarchical group, which is listed
         by group or project name.
.SH -slots output

.sp 2
Displays the following information:
.sp 2
\fB\fRCurrent job slots in use\fB\fR
.br
         The total number of slots currently being used by LSF
         License Scheduler jobs, including \fBtaskman\fR jobs.
.sp 2
\fB\fRPeak job slots used\fB\fR
.br
         The peak number of slots in use since the last time LSF
         License Scheduler was restarted.
.SH Sample output

.sp 2
For example, the blstat command has the following output for a
cluster mode feature:
.sp 2
blstat -t f1000
.br
FEATURE: f1000            
.br
 SERVICE_DOMAIN: Lan12
.br
 TOTAL_TOKENS: 1000 TOTAL_ALLOC: 967  TOTAL_USE: 655  OTHERS: 25  
.br
  CLUSTER     SHARE   ALLOC TARGET INUSE RESERVE OVER  PEAK  BUFFER FREE  DEMAND
.br
  clusterA     66.7 %  647  15     0     655     0     658   100    0     7452 
.br
  clusterB     33.3 %  320  15     0     0       0     0     -      320   0    
.br
 SERVICE_DOMAIN: Lan99
.br
 TOTAL_TOKENS: 2000 TOTAL_ALLOC: 2000 TOTAL_USE: 0    OTHERS: 0   
.br
  CLUSTER     SHARE   ALLOC TARGET INUSE RESERVE OVER  PEAK  BUFFER FREE  DEMAND
.br
  clusterA     25.0 %  500  15     0     0       0     0     100    500   0    
.br
  clusterB     25.0 %  500  15     0     0       0     0     100    500   0    
.br
  clusterC     25.0 %  500  15     0     0       0     0     -      500   0    
.br
  clusterD     25.0 %  500  15     0     0       0     0     -      500   0 
.br

.br

.sp 2
For example, for a project mode feature with a group distribution
configuration the blstat command shows the locality of the
\fRhspice\fR feature that is configured for various sites:
.sp 2
blstat
.br
FEATURE: hspice
.br
 SERVICE_DOMAIN: SD3 SD4
.br
 TOTAL_INUSE: 0    TOTAL_RESERVE: 0    TOTAL_FREE: 22   OTHERS: 0
.br
  PROJECT                 SHARE   OWN  INUSE RESERVE FREE   DEMAND 
.br
  Lp1                     50.0 %   3     1    0        0     11
.br
  Lp2                     50.0 %   1     3    0        0     11
.br
FEATURE: hspice@clusterA
.br
 SERVICE_DOMAIN: SD1
.br
 TOTAL_INUSE: 0    TOTAL_RESERVE: 0    TOTAL_FREE: 25   OTHERS: 0
.br
  PROJECT                 SHARE   OWN  INUSE RESERVE FREE   DEMAND 
.br
  Lp1                     50.0 %   4     0    0      12       3
.br
  Lp2                     50.0 %   5     0    0      13       1
.br
FEATURE: hspice@siteB
.br
 TOTAL_INUSE: 0    TOTAL_RESERVE: 0    TOTAL_FREE: 65   OTHERS: 0
.br
  PROJECT                 SHARE   OWN  INUSE RESERVE FREE   DEMAND 
.br
  Lp1                     50.0 %   4     0    0      32       2
.br
  Lp2                     50.0 %   5     0    0      33       6
.br

.sp 2
For example, for a project mode feature, the blstat -c command
displays the following information:
.sp 2
blstat -c f50
.br
FEATURE: f50
.br
PROJECT         CLUSTER        INUSE   RESERVE   FREE   NEED   ACUM_USE   SCALED_ACUM   AVAIL
.br
myProj2         interactive    0       0         9      0      0.0        0.0           9
.br
                clusterA       0       0         8      0      0.0        0.0           0
.br
                clusterB       0       0         8      0      0.0        0.0           0
.br
default         interactive    0       0         9      0      0.0        0.0           9
.br
                clusterA       0       0         8      0      0.0        0.0           0
.br
                clusterB       0       0         8      0      0.0        0.0           0
.sp 2
For example, for a fast dispatch project mode feature, the blstat
-c command displays the following information:
.sp 2
blstat -c f100
.br
FEATURE: f100
.br
PROJECT     CLUSTER         ALLOC TARGET INUSE  RESERVE OVER  FREE  DEMAND
.br
myProj1     interactive     4     4      0      0       0     4     0
.br
            clusterA        3     3      0      0       0     3     0
.br
            clusterB        3     3      0      0       0     3     0
.br
myProj2     interactive     30    30     0      0       0     30    0
.br
            clusterA        30    30     0      0       0     30    0
.br
            clusterB        30    30     0      0       0     30    0
.SH See also

.sp 2
blhosts, blinfo