
.ad l

.TH fodhosts 1 "June 2016" "" ""n.ll 72

.ce 1000
\fBfodhosts\fR
.ce 0

.sp 2
Displays the status of FOD hosts.
.sp 2

.SH Synopsis

.sp 2
\fBfodhosts\fR [-h | -V]
.SH Description

.sp 2
Lists all FOD hosts and displays status.
.sp 2
The first host listed with \fRok\fR status is the master host..
.SH Options

.sp 2
\fB-h\fR
.br
         Prints command usage to stderr and exits.
.sp 2
\fB-V\fR
.br
         Prints FOD release version to stderr and exits.
.SH Output

.sp 2
\fBHOST_NAME\fR
.br
         Name of FOD host.
.sp 2
\fBSTATUS\fR
.br
         Status of FOD host.
.sp 2
         \fBok\fR
.br
                  FOD is running properly on the host.
.sp 2
         \fBunavail\fR
.br
                  Unavailable. The host may be down or FOD may
                  not be started on the host.
.sp 2
