
.ad l

.TH fodid 1 "June 2016" "" ""n.ll 72

.ce 1000
\fBfodid\fR
.ce 0

.sp 2
Displays FOD master host and version information.
.sp 2

.SH Synopsis

.sp 2
\fBfodid\fR [-h | -V]
.SH Description

.sp 2
Displays name of current master host and current version of FOD.
Confirms that FOD is started and running.
.SH Options

.sp 2
\fB-h\fR
.br
         Prints command usage to stderr and exits.
.sp 2
\fB-V\fR
.br
         Prints FOD release version to stderr and exits.
.sp 2
