
.ad l

.TH lsid 1 "July 2021" "" ""
.ll 72

.ce 1000
\fBlsid\fR
.ce 0

.sp 2
Displays the LSF version number, the cluster name, and the
management host name.
.sp 2

.SH Synopsis

.sp 2
\fBlsid\fR [\fB-h\fR | \fB-V\fR]
.SH Description

.sp 2
The management host is dynamically selected from all hosts in the
cluster.
.sp 2
In LSF multicluster capability, the management host is
dynamically selected from all hosts in the local cluster.
.SH Options

.sp 2
\fB-h\fR
.br
         Prints command usage to stderr and exits.
.sp 2
\fB-V\fR
.br
         Prints LSF release version to stderr and exits.
.SH Files

.sp 2
The host names are defined in the lsf.cluster.\fIcluster_name\fR
file and cluster names are defined in the lsf.shared file.
.SH See also

.sp 2
\fRls_getclustername\fR, \fRls_getmastername\fR, lsinfo