
.ad l

.TH lsportcheck 1 "July 2021" "" ""
.ll 72

.ce 1000
\fBlsportcheck\fR
.ce 0

.sp 2
Displays ports that LSF is currently using or the LSF ports that
will be used before starting LSF.
.sp 2

.SH Synopsis

.sp 2
\fBlsportcheck\fR \fB-l\fR [\fB-m\fR | \fB-s\fR]
.sp 2
\fBlsportcheck\fR [\fB-h\fR]
.SH Description

.sp 2
In UNIX hosts, you must run the lsportcheck command as root to
get complete information on the ports in the operating system.
.sp 2
The lsportcheck command displays both TCP and UDP ports.
.SH Options

.sp 2
\fB-l [-m]\fR
.br
         Displays TCP and UDP ports on the LSF management host.
         Run this command option on the LSF management host.
.sp 2
\fB-l -s\fR
.br
         Displays TCP and UDP ports on the LSF server host. Run
         this command option on the LSF server host.
.sp 2
\fB-h\fR
.br
         Prints command usage and exits.