
.ad l

.TH wgpasswd 1 "July 2021" "" ""
.ll 72

.ce 1000
\fBwgpasswd\fR
.ce 0

.sp 2
Changes a user’s password for a Microsoft Windows workgroup.
.sp 2

.SH Synopsis

.sp 2
\fBwgpasswd\fR [user_name]
.sp 2
\fBwgpasswd\fR [\fB-h\fR]
.SH Description

.sp 2
\fBImportant: \fRYou must run this command on a host in a
Microsoft Windows workgroup. You must have administrative
privileges to change another user’s password.
.sp 2
Prompts for old and new passwords, then changes the password on
every host in the workgroup.
.sp 2
By default, modifies your own user account.
.SH Options

.sp 2
\fB\fIuser_name\fB\fR
.br
         Specifies the account to modify. You must have
         administrative privileges to change another user’s
         password.
.sp 2
\fB-h\fR
.br
         Prints command usage to stderr and exits.
.SH Output

.sp 2
For each host in the workgroup, returns the status of the
operation (\fRSUCCESS\fR or \fRFAILED\fR).
.SH Files

.sp 2
Modifies the LSF password file.