.TH "das_init" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
das_init \- das_init 
Used to initialize the DM library.
.PP
Generally only needed before calling \fBdm_params\fP.
.PP
\fB#include <lsf/dm.def.h>
.br
 include <lsf/dm.api.h>\fP
.PP
\fB int das_init(int options)\fP
.PP
.SH "Parameters:"
\fIoptions\fP This is one or more of DAS_INIT_OPEN_LOGFILE, DAS_INIT_WRITE_STDERR, DAS_INIT_CLIENT_SIDE, DAS_INIT_LSFCONF_ONLY, and DAS_INIT_GET_PARAMS_FROM_DMD 'or'-ed together. Most of the time set options to DAS_INIT_LSFCONF_ONLY.
.PP
.SH "Returns:"
DAS_NO_ERROR 
.br
 Function was successful.
.PP
!DAS_NO_ERROR:One of the values of 'enum dasErrCode'. 
.br
 Function failed. 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
