.TH "das_reset" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
das_reset \- das_reset 
Close any connections to the DM.
.PP
\fB#include <lsf/dm.def.h>
.br
 include <lsf/dm.api.h>\fP
.PP
\fB void das_reset(void)\fP
.PP
.SH "Parameters:" 
.PP
none
.PP
.SH "Returns:"
void:This function returns no value. 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
