.TH "daslib" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
daslib \- daslib 
Application Programming Interface (API) library functions for DM
.PP
.SH "Note:"
.PP
All DASLIB APIs require that the header file <lsf/dm.def.h> and <lsf/dm.api.h> be included.
.PP
.SH "Files:" 
.PP
LSF_CONFDIR/lsf.datamanager.<clustername>
.PP
.SH "See also:"
\fBdas_init\fP 
.PP
\fBdas_perror\fP 
.PP
\fBdas_reset\fP 
.PP
\fBdas_strerror\fP 
.PP
\fBdm_admin\fP 
.PP
\fBdm_cache\fP 
.PP
\fBdm_chgrp\fP 
.PP
\fBdm_chmod\fP 
.PP
\fBdm_clusters\fP 
.PP
\fBdm_delete_tag\fP 
.PP
\fBdm_list_tags\fP 
.PP
\fBdm_local\fP 
.PP
\fBdm_params\fP 
.PP
\fBdm_stage_in\fP 
.PP
\fBdm_stage_out\fP 
.PP
\fBgetRegisteredDmdCluster\fP 
.PP
\fBfreeDmParams\fP 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
