.TH "dm_stage_in" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dm_stage_in \- dm_stage_in 
Use this function to perform stage-in operations.
.PP
If this function is used by an application that is not running as an LSF job, the function fails.
.PP
\fB#include <lsf/dm.def.h>
.br
 include <lsf/dm.api.h>\fP
.PP
\fB int dm_stage_in(struct dmStginRequest* stginReq, char **message)\fP
.PP
.SH "Parameters:"
\fI*stginReq\fP stage-in request structure
.br
\fI**message\fP A string to give extra information about the error, this can be NULL if you don't care
.PP
.SH "Data Structures:" 
.PP
\fBstruct\fP \fBdmStginRequest\fP
.PP
.SH "Returns:"
DAS_NO_ERROR 
.br
 Function was successful.
.PP
-1 
.br
 Function failed.
.PP
.SH "Errors:" 
.PP
If the function fails, daserrno is set to indicate the error. The 'message' argument if initially not NULL; the caller is responsible for freeing the memory (dynamically allocated in the function). 
.PP

.ad l
.nh
.SH NAME
dmStginRequest \- main request data structure for dm_stage_in() API  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBdestPath\fP"
.br
.ti -1c
.RI "struct dmStageinSourceFile \fBsrcFile\fP"
.br
.ti -1c
.RI "struct \fBdmTagInfo\fP \fBtag\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
main request data structure for dm_stage_in() API 
.SH "Field Documentation"
.PP 
.SS "char* \fBdmStginRequest::destPath\fP"
.PP
Optional destination path name - can be a file path or folder path (for ALL or TAG mode). 
.PP

.SS "struct dmStageinSourceFile \fBdmStginRequest::srcFile\fP"
.PP
source file information 
.PP
.SS "struct \fBdmTagInfo\fP \fBdmStginRequest::tag\fP"
.PP
tag information 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
