.TH "extsched_order_getNextJobOfList" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_order_getNextJobOfList \- extsched_order_getNextJobOfList 
Get the next job in the job list.
.PP
\fB#include <lssched.h>\fP
.PP
\fB INT_JobBlock *extsched_order_getNextJobOfList(INT_JobBlock *currJob, INT_JobList *jobList)\fP
.PP
.SH "Parameters:"
\fIcurrJob\fP [IN] : Pointer to the current job. 
.br
\fIjobList\fP [IN] : The passed in job list.
.PP
.SH "Returns:"
INT_JobBlock *  the next job in jobList. 
.PP
NULL  is empty. 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
