.TH "extsched_set_hData" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_set_hData \- extsched_set_hData 
Set the data associated with a hash table entry.
.PP
\fB#include <lssched.h>\fP
.PP
\fB int extsched_set_hData(INT_hEnt *e, void *d)\fP
.PP
.SH "Parameters:"
\fIe\fP [IN|OUT] pointer to a hash table entry 
.br
\fId\fP [IN] pointer to the data
.PP
.SH "Returns:"
int:0 . 
.PP
int:-1 .
.PP
.SH "See also:"
\fBextsched_get_hData\fP 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
