.TH "extsched_job_getextresreq" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_job_getextresreq \- extsched_job_getextresreq 
Get the user-specified resource requirements messages for the job.
.PP
Same as extsched_resreq_getextresreq, but uses pointer to the job, rather than the resource requirements of the peer jobs.
.PP
\fB#include <lssched.h>\fP
.PP
\fB char **extsched_job_getextresreq(INT_JobBlock *jobPtr, int *msgCnt)\fP
.PP
.SH "Parameters:"
\fIjob\fP [IN] : Internal job object. 
.br
\fImsgCnt\fP [OUT] : Number of user-specified messages submitted with the peer jobs.
.PP
.SH "Returns:"
char **  of user-specified messages submitted with the peer jobs. 
.PP
NULL  there are no such messages.
.PP
.SH "See also:"
\fBextsched_resreq_getextresreq\fP 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
