.TH "extsched_order_getJobNumOfList" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_order_getJobNumOfList \- extsched_order_getJobNumOfList 
Get the number of jobs in the job list.
.PP
\fB#include <lssched.h>\fP
.PP
\fB int extsched_order_getJobNumOfList(INT_JobList *jobList)\fP
.PP
.SH "Parameters:"
\fIjobList\fP [IN] : The passed in job list.
.PP
.SH "Returns:"
int  number of jobs in the job list. 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
