.TH "extsched_order_getJobSubmitTime" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_order_getJobSubmitTime \- extsched_order_getJobSubmitTime 
Get the submission time of a job.
.PP
\fB#include <lssched.h>\fP
.PP
\fB time_t extsched_order_getJobSubmitTime(INT_JobBlock *job)\fP
.PP
.SH "Parameters:"
\fIjobPtr\fP [IN] : Internal job object, this is jobblock not INT_Job pointer
.PP
.SH "Returns:"
time_t  the submission time of job. 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
