.TH "extsched_get_INT_Job" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_get_INT_Job \- extsched_get_INT_Job 
This is meant to be used from inside an allocator function.
.PP
Pass in the jobBlock pointer to obtain the corresponding INT_Job pointer.
.PP
\fB#include <lssched.h>\fP
.PP
\fB INT_Job *extsched_get_INT_Job(INT_JobBlock *jobBlock)\fP
.PP
.SH "Parameters:"
\fIjobBlock\fP [IN] : the jobBloack parameter passed into the allocator function
.PP
.SH "Returns:"
INT_Job *  INT_Job pointer, do not free the returned pointer. 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
