.TH "extsched_getEnt_" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_getEnt_ \- extsched_getEnt_ 
Search a hash table for an entry corresponding to key.
.PP
\fB#include <lssched.h>\fP
.PP
\fB INT_hEnt *extsched_getEnt_(INT_hTab *t, const char *k)\fP
.PP
.SH "Parameters:"
\fIt\fP [IN] pointer to a hash table object 
.br
\fIk\fP [IN] key name
.PP
.SH "Returns:"
INT_hEnt *  to an entry object. 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
