.TH "extsched_cand_removehost" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_cand_removehost \- extsched_cand_removehost 
Remove a candidate host from the group.
.PP
Remaining hosts in the group are shifted up to the current index. Thus, do not increment the current index if iterating through the candidate hosts in this group.
.PP
\fB#include <lssched.h>\fP
.PP
\fB void extsched_cand_removehost(struct candHostGroup *group, int index)\fP
.PP
.SH "Parameters:"
\fIgroup\fP [IN/OUT] : group of hosts to be modified 
.br
\fIindex\fP [IN] : index of the candidate host in the group to be removed.
.PP
.SH "Returns:"
void  is no return value. 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
