.TH "extsched_inScout" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_inScout \- extsched_inScout 
This function reports whether it is running in the scout (the child) process, or in the main scheduler (the parent) process.
.PP
\fB#include <lssched.h>\fP
.PP
\fB int extsched_inScout(void)\fP
.PP
.SH "Parameters:" 
.PP
none 
.br
.PP
.SH "Returns:"
int:0  in the main scheduler (the parent) process. 
.PP
int:1  in the scout (the child) process.
.PP
.SH "See also:"
\fBextsched_getScoutMode\fP 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
