.TH "extsched_register_canBePreempted" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_register_canBePreempted \- extsched_register_canBePreempted 
Register a function that will decide if a job can be preempted.
.PP
The registered function will be called during preemption when considering whether a job should be preempted.
.PP
\fB#include <lssched.h>\fP
.PP
\fB int extsched_register_canBePreempted( CanBePreemptedFn canBePreemptedFunc )\fP
.PP
.SH "Parameters:"
\fIcanBePreemptedFunc\fP - (IN) pointer to the function that decides if a job can be preempted
.PP
.SH "Returns:"
int:0  succesfully registered. 
.PP
int:<0  failed to register the function.
.PP
.SH "See also:"
\fBCanBePreemptedFn\fP 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
