.TH "extsched_order_registerOrderFn4AllQueues" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_order_registerOrderFn4AllQueues \- extsched_order_registerOrderFn4AllQueues 
Register a function that decides job dispatch order for all queues.
.PP
\fB#include <lssched.h>\fP
.PP
\fB int extsched_order_registerOrderFn4AllQueues(JobOrderFn4Que  orderFn)\fP
.PP
.SH "Parameters:"
\fIfcfsOrderFn\fP [IN] : Pointer to the function that decides job dispatch order.
.PP
.SH "Returns:"
int:0  registered. 
.PP
int:<0  to register the function.
.PP
.SH "See also:"
\fBJobOrderFn4Que\fP 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
