.TH "extsched_TabEmpty_" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_TabEmpty_ \- extsched_TabEmpty_ 
Check whether the table is empty.
.PP
\fB#include <lssched.h>\fP
.PP
\fB int extsched_TabEmpty_(INT_hTab *t)\fP
.PP
.SH "Parameters:"
\fIt\fP [IN] pointer to a hash table object
.PP
.SH "Returns:"
int:1  is empty. 
.PP
int:0  is not empty. 
.PP
int:-1 , t was NULL. 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
