.TH "extsched_jobArray2Str" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_jobArray2Str \- extsched_jobArray2Str 
Create a string containing a job array id.
.PP
\fB#include <lssched.h>\fP
.PP
\fB char *extsched_jobArray2Str(\fBJobArrayID_T\fP *jarrayid)\fP
.PP
.SH "Parameters:"
\fIjarrayid\fP [IN] job array id
.PP
.SH "Returns:"
char *  to a string containing a job array id (should NOT be freed). 
.PP
NULL . 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
