.TH "extsched_createTab" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_createTab \- extsched_createTab 
Create an un-initialized hash table object.
.PP
You probabably should use extsched_createTabAndInit().
.PP
\fB#include <lssched.h>\fP
.PP
\fB INT_hTab *extsched_createTab(void)\fP
.PP
.SH "Parameters:" 
.PP
none 
.br
.PP
.SH "Returns:"
INT_hTab *  to a (un-initialized) hash table object.
.PP
.SH "See also:"
\fBextsched_initTab_\fP 
.PP
\fBextsched_createTabAndInit\fP 
.PP
\fBextsched_destroyTab\fP 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
