.TH "extsched" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched \- extsched 
Application Programming Interface (API) functions for scheduler plugins.
.PP
.SH "Note:"
.PP
All EXTSCHED APIs require that the header file <lssched.h> be included.
.PP
.SH "See also:"
\fBextsched_TabEmpty_\fP 
.PP
\fBextsched_addAllocLimit\fP 
.PP
\fBextsched_addEnt_\fP 
.PP
\fBextsched_alloc_gethostslot\fP 
.PP
\fBextsched_alloc_modify\fP 
.PP
\fBextsched_alloc_registerallocator\fP 
.PP
\fBextsched_alloc_type\fP 
.PP
\fBextsched_cand_getavailslot\fP 
.PP
\fBextsched_cand_getnextgroup\fP 
.PP
\fBextsched_cand_removehost\fP 
.PP
\fBextsched_clustername\fP 
.PP
\fBextsched_createTab\fP 
.PP
\fBextsched_createTabAndInit\fP 
.PP
\fBextsched_create_sTab\fP 
.PP
\fBextsched_delRef_\fP 
.PP
\fBextsched_destroyTab\fP 
.PP
\fBextsched_destroy_sTab\fP 
.PP
\fBextsched_determineEvent\fP 
.PP
\fBextsched_firstEnt_\fP 
.PP
\fBextsched_freeAlloc\fP 
.PP
\fBextsched_freeAllocLimitList\fP 
.PP
\fBextsched_freeIntAlloc\fP 
.PP
\fBextsched_freeJobInfo\fP 
.PP
\fBextsched_freeRefTab_\fP 
.PP
\fBextsched_freeRsrcReqInfo\fP 
.PP
\fBextsched_freeTab_\fP 
.PP
\fBextsched_getAlloc\fP 
.PP
\fBextsched_getAllocLimitList\fP 
.PP
\fBextsched_getCheckAllocContext\fP 
.PP
\fBextsched_getChunkRef\fP 
.PP
\fBextsched_getEnt_\fP 
.PP
\fBextsched_getHost\fP 
.PP
\fBextsched_getHostID\fP 
.PP
\fBextsched_getJobAlloc\fP 
.PP
\fBextsched_getJobInfo\fP 
.PP
\fBextsched_getPreemptableJobs\fP 
.PP
\fBextsched_getResType\fP 
.PP
\fBextsched_getRsrcReqForJob\fP 
.PP
\fBextsched_getRsrcReqInfo\fP 
.PP
\fBextsched_getSchedJobModError\fP 
.PP
\fBextsched_getScoutMode\fP 
.PP
\fBextsched_get_INT_Job\fP 
.PP
\fBextsched_get_hData\fP 
.PP
\fBextsched_get_key\fP 
.PP
\fBextsched_host_resources\fP 
.PP
\fBextsched_inScout\fP 
.PP
\fBextsched_initTab_\fP 
.PP
\fBextsched_isEstimatorMode\fP 
.PP
\fBextsched_jobArray2Str\fP 
.PP
\fBextsched_job_getaskedslot\fP 
.PP
\fBextsched_job_getextresreq\fP 
.PP
\fBextsched_modifyJob\fP 
.PP
\fBextsched_nextEnt_\fP 
.PP
\fBextsched_order_getFirstJobOfList\fP 
.PP
\fBextsched_order_getJobNumOfList\fP 
.PP
\fBextsched_order_getJobPriority\fP 
.PP
\fBextsched_order_getJobSeqNum\fP 
.PP
\fBextsched_order_getJobSubmitTime\fP 
.PP
\fBextsched_order_getJobUser\fP 
.PP
\fBextsched_order_getNextJobOfList\fP 
.PP
\fBextsched_order_getPreJobOfList\fP 
.PP
\fBextsched_order_isJobListEmpty\fP 
.PP
\fBextsched_order_registerOrderFn4AllQueues\fP 
.PP
\fBextsched_reason_set\fP 
.PP
\fBextsched_register_canBePreempted\fP 
.PP
\fBextsched_register_jobEventCallback\fP 
.PP
\fBextsched_resetJob\fP 
.PP
\fBextsched_resreq_getextresreq\fP 
.PP
\fBextsched_resreq_getqueextsched\fP 
.PP
\fBextsched_resreq_registerhandler\fP 
.PP
\fBextsched_resreq_setobject\fP 
.PP
\fBextsched_rmEntAndFreeData\fP 
.PP
\fBextsched_rmEnt_\fP 
.PP
\fBextsched_setMainReason\fP 
.PP
\fBextsched_set_hData\fP 
.PP
.PP
\fBRsrcReqHandler_CheckAllocFn\fP 
.PP
\fBRsrcReqHandler_FreeFn\fP 
.PP
\fBRsrcReqHandler_NewFn\fP 
.PP
\fBRsrcReqHandler_NotifyAllocFn\fP 
.PP
\fBRsrcReqHandler_SortFn\fP 
.PP
\fBAllocatorFn\fP 
.PP
\fBJobOrderFn4Que\fP 
.PP
\fBCanBePreemptedFn\fP 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
