.TH "extsched_createTabAndInit" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_createTabAndInit \- extsched_createTabAndInit 
Create and initialize a hash table object.
.PP
\fB#include <lssched.h>\fP
.PP
\fB INT_hTab *extsched_createTabAndInit(int slots)\fP
.PP
.SH "Parameters:"
\fIslots\fP [IN] number of slots
.PP
.SH "Returns:"
INT_hTab *  to a hash table object.
.PP
.SH "See also:"
\fBextsched_destroyTab\fP 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
