.TH "extsched_alloc_gethostslot" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_alloc_gethostslot \- extsched_alloc_gethostslot 
Get the distribution of slots on various candidate hosts in job's allocation.
.PP
\fB#include <lssched.h>\fP
.PP
\fB struct hostSlot *extsched_alloc_gethostslot(INT_Alloc *alloc, INT_CandGroupList *candGroupList, int *hostCnt, struct candHostGroup **group)\fP
.PP
.SH "Parameters:"
\fIalloc\fP [IN] : Internal allocation object. Allocated slots for the job. 
.br
\fIcandGroupList\fP [IN] : list of candidate host groups for the job. 
.br
\fIhostCnt\fP [OUT] : number of hostSlot information returned. 
.br
\fIgroup\fP [OUT] : which candidate host group is allocated.
.PP
.SH "Returns:"
struct hostSlot *  of hostSlot data structures, giving the number of slots given to the job on each host, and slots available on the host. 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
