.TH "extsched_clustername" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_clustername \- extsched_clustername 
Returns the local cluster's name.
.PP
Do not free the returned pointer.
.PP
\fB#include <lssched.h>\fP
.PP
\fB char *extsched_clustername(void)\fP
.PP
.SH "Parameters:" 
.PP
none 
.br
.PP
.SH "Returns:"
char *  the local cluster's name. 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
