.TH "extsched_getSchedJobModError" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_getSchedJobModError \- extsched_getSchedJobModError 
This call reports success/failure about the last call to extsched_modifyJob or extsched_resetJob for jobs.
.PP
The associated job array is broken into elements and the LSBE_* error is determined. If the LSBE error is 0 it means the call extsched_resetJob/extsched_modifyJob was ultimately successful, or it was never called. If a call to extsched_resetJob/extsched_modifyJob is made in the current session then the success/failure should be known in the next session.
.PP
NOTE: The caller is responsible to free jobList and errList. Remember to free clusterId in each element of jobList.
.PP
\fB#include <lssched.h>\fP
.PP
\fB int extsched_getSchedJobModError(INT_Job *job, int *nElem, extsched_JobElement **jobList, int **errList)\fP
.PP
.SH "Parameters:"
\fIjob\fP [IN] : internal representation of a job 
.br
\fInElem\fP [OUT] : number of elements in jobList and errList 
.br
\fIjobList\fP [OUT] : list of job elements 
.br
\fIerrList\fP [OUT] : list of LSBE_* error number of last call to extsched_resetJob/extsched_modifyJob
.PP
.SH "Returns:"
int:0 . 
.PP
int:-1 .
.PP
.SH "See also:"
\fBextsched_resetJob\fP 
.PP
\fBextsched_modifyJob\fP 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
