.TH "extsched_getJobInfo" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_getJobInfo \- extsched_getJobInfo 
Routine to extract info from the internal representation of a job.
.PP
Caller should invoke extsched_freeJobInfo() to free the returned info structure.
.PP
\fB#include <lssched.h>\fP
.PP
\fB int extsched_getJobInfo(INT_Job *job, struct jobInfo *info)\fP
.PP
.SH "Parameters:"
\fIjob\fP [IN] : internal representation of a job 
.br
\fIinfo\fP [OUT] : info extracted from the job
.PP
.SH "Returns:"
int:0 . 
.PP
int:-1 . 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
