.TH "extsched_getRsrcReqInfo" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_getRsrcReqInfo \- extsched_getRsrcReqInfo 
Routine creates extsched_rsrcReqInfo object that exposes part of the job's internal resrource requirement.
.PP
Currently it exposes the job's select string, and the job's requested resource usage.
.PP
The caller is responsible to free the returned data by using extsched_freeRsrcReqInfo().
.PP
\fB#include <lssched.h>\fP
.PP
\fB extsched_rsrcReqInfo *extsched_getRsrcReqInfo(INT_RsrcReq *rsrcreq)\fP
.PP
PARAMETERS
.PP
.SH "Parameters:"
\fIrsrcreq\fP [IN] : internal representation of rsrcreq
.PP
.SH "Returns:"
extsched_rsrcReqInfo *  to a dynamically allocated extsched_rsrcReqInfo data object.
.PP
.SH "See also:"
\fBextsched_freeRsrcReqInfo\fP 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
