.TH "extsched_initTab_" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_initTab_ \- extsched_initTab_ 
Initialize a hash table object.
.PP
\fB#include <lssched.h>\fP
.PP
\fB extsched_initTab_(INT_hTab *t, int slots)\fP
.PP
.SH "Parameters:"
\fIt\fP [IN|OUT] pointer to a hash table object 
.br
\fIslots\fP [IN] number of slots
.PP
.SH "Returns:"
void  is no return value. 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
