.TH "extsched_order_getJobSeqNum" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_order_getJobSeqNum \- extsched_order_getJobSeqNum 
Get the sequence number of a job.
.PP
Sequence number is used by LSF internally to decide a job's FCFS priority in a queue. Beside a job's submission time, btop/bbot and other relevant features; e.g, job requeue, are also considered when determining a job's sequential number.
.PP
\fB#include <lssched.h>\fP
.PP
\fB unsigned int extsched_order_getJobSeqNum(INT_JobBlock *job)\fP
.PP
.SH "Parameters:"
\fIjobPtr\fP [IN] : Internal job object, this is jobblock not INT_Job pointer
.PP
.SH "Returns:"
unsigned int  the sequence number of a job. 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
