.TH "extsched_order_getJobUser" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_order_getJobUser \- extsched_order_getJobUser 
Get the user name of a job.
.PP
\fB#include <lssched.h>\fP
.PP
\fB char *extsched_order_getJobUser(INT_JobBlock *job)\fP
.PP
.SH "Parameters:"
\fIjobPtr\fP [IN] : Internal job object, this is jobblock not INT_Job pointer
.PP
.SH "Returns:"
char *  the user name of job. 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
