.TH "extsched_getScoutMode" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_getScoutMode \- extsched_getScoutMode 
To be called from within the scout process.
.PP
Reports the mode.
.PP
\fB#include <lssched.h>\fP
.PP
\fB int extsched_getScoutMode(void)\fP
.PP
.SH "Parameters:" 
.PP
none 
.br
.PP
.SH "Returns:"
int:0  not in scout 
.PP
int:1  determine future allocations
.PP
.SH "See also:"
\fBextsched_inScout\fP 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
