.TH "extsched_resreq_getqueextsched" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_resreq_getqueextsched \- extsched_resreq_getqueextsched 
Get queue level MANDATORY_EXTSCHED and DEFAULT_EXTSCHED for job.
.PP
\fB#include <lssched.h>\fP
.PP
\fB int extsched_resreq_getqueextsched(INT_RsrcReq *resreq, char **mand_extsched, char **default_extsched)\fP
.PP
.SH "Parameters:"
\fIresreq\fP [IN] : Internal object representing resource requirements for peer jobs. 
.br
\fImand_extsched\fP [OUT] : return the setting of MANDATORY_EXSCHED of job queue, mand_extsched should not be NULL. 
.br
\fIdefault_extsched\fP [OUT] : return the setting of DEFAULT_EXSCHED of job queue, default_extsched should not be NULL.
.PP
.SH "Returns:"
int:0 . 
.PP
int:-1 .
.PP
If MANDATORY_EXTSCHED has been set in job's queue, *mand_extsched will points to the string, otherwise it will be NULL. If DEFAULT_EXTSCHED has been set in job's queue, *default_extsched will points to the string, otherwise it will be NULL. 
.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
