.TH "extsched_get_key" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_get_key \- extsched_get_key 
Retreive the key associated with a hash table entry.
.PP
\fB#include <lssched.h>\fP
.PP
\fB char *extsched_get_key(INT_hEnt *e)\fP
.PP
.SH "Parameters:"
\fIe\fP [IN] pointer to a hash table entry
.PP
.SH "Returns:"
char *  to the key name. 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
