.TH "extsched_destroy_sTab" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_destroy_sTab \- extsched_destroy_sTab 
Free the search table object.
.PP
\fB#include <lssched.h>\fP
.PP
\fB void extsched_destroy_sTab(INT_sTab **s)\fP
.PP
.SH "Parameters:"
\fIs\fP [IN|OUT] search object
.PP
.SH "Returns:"
void  is no return value.
.PP
.SH "See also:"
\fBextsched_create_sTab\fP 
.PP
\fBextsched_firstEnt_\fP 
.PP
\fBextsched_nextEnt_\fP 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
