.TH "extsched_resreq_registerhandler" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_resreq_registerhandler \- extsched_resreq_registerhandler 
Register a new handler for job resource requirements.
.PP
Registered handler functions will be called during scheduling to handle peer jobs' resource requirements.
.PP
The handlerId must be a number between 100 and 199. Each handler must have a different identifier.
.PP
Fields of RsrcReqHandlerType that are not used must be set to NULL.
.PP
\fB#include <lssched.h>\fP
.PP
\fB int extsched_resreq_registerhandler(int handlerId, RsrcReqHandlerType *handler)\fP
.PP
.SH "Parameters:"
\fIhandlerId\fP [IN] : identifier for the handler 
.br
\fIhandler\fP [IN] : pointer to the handler. Memory must be dynamically allocated. Memory must not be freed.
.PP
.SH "Returns:"
int:TRUE . 
.PP
int:FALSE .
.PP
.SH "See also:"
\fBRsrcReqHandlerType\fP 
.PP
\fBRsrcReqHandler_NewFn\fP 
.PP
\fBRsrcReqHandler_FreeFn\fP 
.PP
\fBRsrcReqHandler_MatchFn\fP 
.PP
\fBRsrcReqHandler_SortFn\fP 
.PP
\fBRsRcReqHandler_NotifyAlloc\fP 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
