.TH "extsched_freeRefTab_" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_freeRefTab_ \- extsched_freeRefTab_ 
Free the hash table used as reference.
.PP
When more than one table contains addresses of the same data structure in memory then only the first hash table has to destroy the data, the other tables, called reference tables just need to destroy their entries.
.PP
\fB#include <lssched.h>\fP
.PP
\fB void extsched_freeRefTab_(INT_hTab **t, int freeTabFlag)\fP
.PP
.SH "Parameters:"
\fIt\fP [IN|OUT] hash table object 
.br
\fIfreeTabFlag\fP [IN] if TRUE the table object is freed and pointer set to NULL, otherwise the table object is in an uninitialized state
.PP
.SH "Returns:"
void  is no return value. 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
