.TH "extsched_getCheckAllocContext" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_getCheckAllocContext \- extsched_getCheckAllocContext 
Function to be called from within checkAllocFn to determine the context in which this function is called.
.PP
\fB#include <lssched.h>\fP
.PP
\fB extsched_SchedContext extsched_getCheckAllocContext(void)\fP
.PP
.SH "Parameters:" 
.PP
none 
.br
.PP
.SH "Returns:"
extsched_SchedContext  scheduling context. One of the SCHED_CONTEXT_* values. 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
