.TH "extsched_getHost" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_getHost \- extsched_getHost 
Obtain a pointer to internal host data.
.PP
\fB#include <lssched.h>\fP
.PP
\fB INT_Host *extsched_getHost(char *hostname, char *clustername)\fP
.PP
.SH "Parameters:"
\fIhostname\fP [IN] : the name of the host 
.br
\fIclustername\fP [IN] : the name of the cluster
.PP
.SH "Returns:"
INT_Host *  to internal host data. 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
