.TH "extsched_create_sTab" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_create_sTab \- extsched_create_sTab 
Create a search table object.
.PP
\fB#include <lssched.h>\fP
.PP
\fB INT_sTab *extsched_create_sTab(void)\fP
.PP
.SH "Parameters:" 
.PP
none 
.br
.PP
.SH "Returns:"
INT_sTab *  to a search object.
.PP
.SH "See also:"
\fBextsched_destroy_sTab\fP 
.PP
\fBextsched_firstEnt_\fP 
.PP
\fBextsched_nextEnt_\fP 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
