.TH "extsched_getHostID" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_getHostID \- extsched_getHostID 
This function will provide the host ID (hostname and clusternam) provided with the internal host pointer.
.PP
This function will allocate the memory for the hostname and clustername so the caller is responsible to free.
.PP
\fB#include <lssched.h>\fP
.PP
\fB int extsched_getHostID(INT_Host *hostPtr, char **hostname, char **clustername)\fP
.PP
.SH "Parameters:"
\fIhostPtr\fP [IN] : pointer to internal host data 
.br
\fIhostname\fP [OUT] : the name of the host 
.br
\fIclustername\fP [OUT] : the name of the cluster the host belongs to
.PP
.SH "Returns:"
int:0 . 
.PP
int:-1 . 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
