.TH "extsched_job_getaskedslot" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_job_getaskedslot \- extsched_job_getaskedslot 
Get the number of slots requested by a job.
.PP
\fB#include <lssched.h>\fP
.PP
\fB int extsched_job_getaskedslot(INT_JobBlock *jobPtr)\fP
.PP
.SH "Parameters:"
\fIjobPtr\fP [IN] : Internal job object.
.PP
.SH "Returns:"
int  (max) number of slots requested by job. 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
