.TH "extsched_setMainReason" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_setMainReason \- extsched_setMainReason 
Set the main pending reason (not host based).
.PP
PEND_EXTSCHED_REASON
.PP
\fB#include <lssched.h>\fP
.PP
\fB int extsched_setMainReason(INT_Reason *reason, char *msg, int bucketLevel)\fP
.PP
.SH "Parameters:"
\fIreason\fP [IN] : internal representation of a pending reason 
.br
\fImsg\fP [IN] : a description of why the reason is being set 
.br
\fIbucketLevel\fP [IN] : if FALSE the pending reason applies specifically to the job
.PP
.SH "Returns:"
int:0 . 
.PP
int:-1 . 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
