.TH "extsched_freeRsrcReqInfo" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_freeRsrcReqInfo \- extsched_freeRsrcReqInfo 
The counterpart for extsched_getRsrcReqInfo() to free the returned object.
.PP
\fB#include <lssched.h>\fP
.PP
\fB void extsched_freeRsrcReqInfo(extsched_rsrcReqInfo **info)\fP
.PP
.SH "Parameters:"
\fIinfo\fP [IN|OUT] : extsched_rsrcReqInfo data to be freed
.PP
.SH "Returns:"
void  is no return value.
.PP
.SH "See also:"
\fBextsched_getRsrcReqInfo\fP 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
