.TH "extsched_destroyTab" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_destroyTab \- extsched_destroyTab 
Free the hash table object.
.PP
The table should be emptied first.
.PP
\fB#include <lssched.h>\fP
.PP
\fB void extsched_destroyTab(INT_hTab **t)\fP
.PP
.SH "Parameters:"
\fIt\fP [IN|OUT] a hash table
.PP
.SH "Returns:"
void  is no return value.
.PP
.SH "See also:"
\fBextsched_createTabAndInit\fP 
.PP
\fBextsched_createTab\fP 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
