.TH "extsched_register_jobEventCallback" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_register_jobEventCallback \- extsched_register_jobEventCallback 
This function is used by a plugin to register a callback function for job events.
.PP
Event definitions used by job event callback functions (JobEventCallbackFn) and used when using extsched_register_jobEventCallback().
.PP
EVENT_JOB_NOTIFICATION_CREATE_JOB a job has been created within the mbschd, usually happens after a job has been submitted EVENT_JOB_NOTIFICATION_DONE_JOB a job is about the be deleted within the mbschd, usually happens after a job is done, exited, or killed
.PP
Flag definitions used by job event callback functions (JobEventCallbackFn).
.PP
FLAG_JOB_NOTIFICATION_DURING_STARTUP the mbsched has just be (re)started, and it is before the first scheduling session FLAG_JOB_NOTIFICATION_REINSERT a job has been recreated within the mbschd, usually happens because a job has been requeued or migrated
.PP
The job event callback function signature.
.PP
typedef void (*JobEventCallbackFn)(\fBJobArrayID_T\fP *jarrayid, INT_Job *job, int event, int flag);
.PP
jarrayid [IN] job array id job [IN] job pointer (job subarray pointer) event [IN] events defined above flag [IN] bit field, flag defined above, can be 0
.PP
\fB#include <lssched.h>\fP
.PP
\fB int extsched_register_jobEventCallback(JobEventCallbackFn, int event)\fP
.PP
.SH "Parameters:"
\fIJobEventCallbackFn\fP [IN] pointer to callback function 
.br
\fIevent\fP [IN] bit field, evnets defined above
.PP
.SH "Returns:"
int:0 . 
.PP
int:-1 . 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
