.TH "extsched_rmEnt_" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_rmEnt_ \- extsched_rmEnt_ 
Remove the given hash table entry and free memory associated with it, but do not free hData.
.PP
\fB#include <lssched.h>\fP
.PP
\fB void extsched_rmEnt_(INT_hTab *t, INT_hEnt *e)\fP
.PP
.SH "Parameters:"
\fIt\fP [IN|OUT] pointer to a hash table object 
.br
\fIe\fP [IN|OUT] pointer to entry object
.PP
.SH "Returns:"
void  is no return value. 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
