.TH "extsched_get_hData" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_get_hData \- extsched_get_hData 
Retreive the data associated with a hash table entry.
.PP
\fB#include <lssched.h>\fP
.PP
\fB void *extsched_get_hData(INT_hEnt *e)\fP
.PP
.SH "Parameters:"
\fIe\fP [IN] pointer to a hash table entry
.PP
.SH "Returns:"
void *  to the data associated with the entry.
.PP
.SH "See also:"
\fBextsched_set_hData\fP 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
