.TH "extsched_cand_getavailslot" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_cand_getavailslot \- extsched_cand_getavailslot 
Get number of available slots on a candidate host.
.PP
This function can also be used to get candidate host name, which is retruned in hostSlot.
.PP
\fB#include <lssched.h>\fP
.PP
\fB struct hostSlot *extsched_cand_getavailslot(struct candHost *candHost)\fP
.PP
.SH "Parameters:"
\fIcandHost\fP [IN] : host to get slot availability from.
.PP
.SH "Returns:"
struct hostSlot *  slots on host. 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
