.TH "extsched_getAllocLimitList" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_getAllocLimitList \- extsched_getAllocLimitList 
An allocation limit list is generated during a call to checkAllocFn.
.PP
Each registered checkAllocFn can add limits to this list, which serves to communicate to the scheduler framework whether the given allocation is permitted or not.
.PP
extsched_getAllocLimitListInfo() generates info on the internal allocation limit list data structure. It is intended to be called from within a checkAllocFn.
.PP
Caller should free the allocated data using the function extsched_freeAllocLimitListInfo().
.PP
\fB#include <lssched.h>\fP
.PP
\fB int extsched_getAllocLimitList(INT_AllocLimitList *allocLimitList, extsched_AllocLimitList **infoPtr)\fP
.PP
.SH "Parameters:"
\fIallocLimitList\fP [IN] : an allocation limit list 
.br
\fIinfoPtr\fP [OUT] : info describing the list
.PP
.SH "Returns:"
int:0 . 
.PP
int:-1 .
.PP
.SH "See also:"
\fBextsched_getAllocLimitListInfo\fP 
.PP
\fBextsched_freeAllocLimitListInfo\fP 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
