.TH "extsched_addEnt_" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extsched_addEnt_ \- extsched_addEnt_ 
Add a new entry in hash table.
.PP
If the entry already exists, then nothing is done. If the 'n' parameter is not NULL and the entry returned is new then 'n' will be set to TRUE, and FALSE if an entry already exists with the given key.
.PP
\fB#include <lssched.h>\fP
.PP
\fB INT_hEnt *extsched_addEnt_(INT_hTab *t, const char *k, int *n)\fP
.PP
.SH "Parameters:"
\fIt\fP [IN|OUT] pointer to a hash table object 
.br
\fIk\fP [IN] key name 
.br
\fIn\fP [OUT] new flag, can be NULL
.PP
.SH "Returns:"
INT_hEnt *  return value is a pointer to the entry. 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
