.TH "getRegisteredDmdCluster" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
getRegisteredDmdCluster \- getRegisteredDmdCluster 
This is a helper function that is used when a 'struct remoteDMs' is needed by some of the other APIs for communicating with a remote DM.
.PP
The remote DM must be known to the local DM for this function to succeed.
.PP
\fB#include <lsf/dm.def.h>
.br
 include <lsf/dm.api.h>\fP
.PP
\fB int getRegisteredDmdCluster(char *clusterName, struct \fBremoteDMs\fP **remoteDMs)\fP
.PP
.SH "Parameters:"
\fI*clusterName\fP Remote cluster name, the remote cluster that is the eventual communication target.
.br
\fI**remoteDMs\fP A dynamically-allocated 'struct remoteDMs'.
.PP
.SH "Data Structures:" 
.PP
\fBstruct\fP \fBremoteDMs\fP
.PP
.SH "Returns:"
DAS_NO_ERROR 
.br
 Function was successful.
.PP
< 0 
.br
 Function failed.
.PP
.SH "Errors:" 
.PP
If the function fails, daserrno is set to indicate the error. 
.PP

.ad l
.nh
.SH NAME
remoteDMs \- used by dm_cache(), dm_list_tags(), dm_delete_tag(), dm_chgrp(), dm_chmod(), getRegisteredDmdCluster() APIs  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBclustername\fP"
.br
.ti -1c
.RI "char * \fBservers\fP"
.br
.ti -1c
.RI "int \fBport\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
used by dm_cache(), dm_list_tags(), dm_delete_tag(), dm_chgrp(), dm_chmod(), getRegisteredDmdCluster() APIs 
.SH "Field Documentation"
.PP 
.SS "char* \fBremoteDMs::clustername\fP"
.PP
lsf cluster name 
.PP
.SS "char* \fBremoteDMs::servers\fP"
.PP
space separated list of host names where dmd runs 
.PP
.SS "int \fBremoteDMs::port\fP"
.PP
port dmd is listening on 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
