.TH "ls_createdir" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ls_createdir \- ls_createdir 
creates a directory on a remote host.
.PP
This routine creates a directory on the remote host.
.PP
\fBls_createdir\fP creates the named directory path on the remote host.
.PP
RES must be running on the remote host.
.PP
\fBls_initrex\fP must be called before calling this function.
.PP
\fB #include <sys/types.h> 
.br
 #include <unistd.h> 
.br
 #include <sys/stat.h> 
.br
 #include <fcntl.h> 
.br
 #include <limits.h> 
.br
 #include <lsf/lsf.h>\fP
.PP
\fB int ls_createdir(char *host, char *path, int userId) \fP
.PP
.SH "Parameters:"
\fI*host\fP The host for the new directory. 
.br
\fI*path\fP The path name for the new directory.
.PP
.SH "Data Structures:" 
.PP
none
.PP
.SH "Define Statements:" 
.PP
none
.PP
.SH "Returns:"
int: 0 
.br
 0 indicates a successful creation.
.PP
int:-1 
.br
 Function failed.
.PP
.SH "Errors:" 
.PP
If the function fails, lserrno is set to indicate the error.
.PP
.SH "Equivalent line commands:" 
.PP
none
.PP
.SH "Files:" 
.PP
none 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
