.TH "lsb_signaljobarray_ex" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lsb_signaljobarray_ex \- lsb_signaljobarray_ex 
Sends a signal to a job array.
.PP
Generally, use \fBlsb_signaljobarray_ex\fP to apply any UNIX signal to a job array or process.
.PP
Any program using this API must be setuid to root if LSF_AUTH is not defined in the lsf.conf file.
.PP
\fB#include <lsf/lsbatch.h>\fP
.PP
\fB int lsb_signaljobarray_ex (struct \fBjobArrayID\fP *id, int signal, int flag, struct \fBsignalExt\fP *)\fP
.PP
.SH "Parameters:"
\fIid\fP The job array id to be signaled. If a job in a job array is to be signaled, use the array form jobID[ i ] where jobID is the job array name, and i is the index value. 
.br
\fIsignal\fP SIGSTOP, SIGCONT, SIGKILL. 
.br
\fI*sigExt\fP The external information.
.PP
.SH "Data Structures:" 
.PP
\fBsignalExt\fP
.PP
.SH "Define Statements:" 
.PP
\fBlsb_submit_options4\fP
.PP
.SH "Returns:"
int:0 
.br
 The function was successful. 
.PP
int:-1 
.br
 The function failed.
.PP
.SH "Errors:" 
.PP
If the function fails, lsberrno is set to indicate the error.
.PP
.SH "Equivalent line commands:" 
.PP
bkill 
.br
.PP
.SH "Files:" 
.PP
${LSF_ENVDIR:-/etc}/lsf.conf
.PP
.SH "See also:"
\fBlsb_signaljobarray\fP 
.PP

.ad l
.nh
.SH NAME
signalExt \- Exteral job signal information.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBreason\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Exteral job signal information. 
.SH "Field Documentation"
.PP 
.SS "char* \fBsignalExt::reason\fP"
.PP
Job kill/stop/resume reason. 
.PP


.ad l
.nh
.SH NAME
lsb_submit_options4 \- define statements used by \fBlsb_submit\fP.  

.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBSUB4_AC_TEMPLATE_NONE\fP   0x00000001"
.br
.ti -1c
.RI "#define \fBSUB4_AC_TEMPLATE\fP   0x00000002"
.br
.ti -1c
.RI "#define \fBSUB4_AC_MTYPE_VM\fP   0x00000004"
.br
.ti -1c
.RI "#define \fBSUB4_AC_MTYPE_PM\fP   0x00000008"
.br
.ti -1c
.RI "#define \fBSUB4_AC_PREEMPTACTION_VM\fP   0x00000010"
.br
.ti -1c
.RI "#define \fBSUB4_AC_MTYPE_ANY\fP   0x00000020"
.br
.ti -1c
.RI "#define \fBSUB4_OUTDIR\fP   0x00000040"
.br
.ti -1c
.RI "#define \fBSUB4_CLUSTER\fP   0x00000080"
.br
.ti -1c
.RI "#define \fBSUB4_NETWORK\fP   0x00000200"
.br
.ti -1c
.RI "#define \fBSUB4_CPU_FREQUENCY\fP   0x00000800"
.br
.ti -1c
.RI "#define \fBSUB4_EXCLUDE_FS_UGROUP\fP   0x00001000"
.br
.ti -1c
.RI "#define \fBSUB4_ENERGY_POLICY_DATA\fP   0x00002000"
.br
.ti -1c
.RI "#define \fBSUB4_ENERGY_POLICY\fP   0x00004000"
.br
.ti -1c
.RI "#define \fBSUB4_ORPHAN_TERM_NO_WAIT\fP   0x00008000"
.br
.ti -1c
.RI "#define \fBSUB4_HOST_FILE\fP   0x00010000"
.br
.ti -1c
.RI "#define \fBSUB4_MEM_SWAP_HOST_LIMIT\fP   0x00020000"
.br
.ti -1c
.RI "#define \fBSUB4_SUBMISSION_ENV_VARS\fP   0x00040000"
.br
.ti -1c
.RI "#define \fBSUB4_AC_MIGRATABLE\fP   0x00080000"
.br
.ti -1c
.RI "#define \fBSUB4_AC_NOT_MIGRATABLE\fP   0x00100000"
.br
.ti -1c
.RI "#define \fBSUB4_DATA_STAGING_REQ\fP   0x00200000"
.br
.ti -1c
.RI "#define \fBSUB4_DATA_TRANSFER_JOB\fP   0x00400000"
.br
.ti -1c
.RI "#define \fBSUB4_DATA_USER_GROUP\fP   0x00800000"
.br
.ti -1c
.RI "#define \fBSUB4_COLLECT_ENERGY_RELATED_USAGE\fP   0x01000000"
.br
.ti -1c
.RI "#define \fBSUB4_PEND_TIME_LIMIT\fP   0x02000000"
.br
.ti -1c
.RI "#define \fBSUB4_ELIGIBLE_PEND_TIME_LIMIT\fP   0x04000000"
.br
.ti -1c
.RI "#define \fBSUB4_WITHOUT_CMD\fP   0x08000000"
.br
.ti -1c
.RI "#define \fBSUB4_GPU_REQ\fP   0x10000000"
.br
.ti -1c
.RI "#define \fBSUB4_GROUP_TRANSF_REQ\fP   0x20000000"
.br
.ti -1c
.RI "#define \fBSUB4_STAGE\fP   0x40000000"
.br
.ti -1c
.RI "#define \fBSUB4_PLAN\fP   0x80000000"
.br
.in -1c
.SH "Detailed Description"
.PP 
define statements used by \fBlsb_submit\fP. 
.SH "Define Documentation"
.PP 
.SS "#define SUB4_AC_TEMPLATE_NONE   0x00000001"
.PP
Dynamic Cluster template 'none' specified. 
.PP
.SS "#define SUB4_AC_TEMPLATE   0x00000002"
.PP
Job submitted with a Dynamic Cluster template specified. 
.PP
.SS "#define SUB4_AC_MTYPE_VM   0x00000004"
.PP
a virtual machine requested 
.PP
.SS "#define SUB4_AC_MTYPE_PM   0x00000008"
.PP
physical machines requested 
.PP
.SS "#define SUB4_AC_PREEMPTACTION_VM   0x00000010"
.PP
Job action when VM is being preempted. 
.PP
.SS "#define SUB4_AC_MTYPE_ANY   0x00000020"
.PP
'any' machines requested 
.PP
.SS "#define SUB4_OUTDIR   0x00000040"
.PP
output directory 
.PP
.SS "#define SUB4_CLUSTER   0x00000080"
.PP
Flag to indicate numAskedClusters parameter has data. 
.PP
Equivalent to bsub -cluster command line option existence. 
.SS "#define SUB4_NETWORK   0x00000200"
.PP
Job carry network requirement. 
.PP
.SS "#define SUB4_CPU_FREQUENCY   0x00000800"
.PP
cpu frequency requirement 
.PP
.SS "#define SUB4_EXCLUDE_FS_UGROUP   0x00001000"
.PP
exclude fairshare user groups 
.PP
.SS "#define SUB4_ENERGY_POLICY_DATA   0x00002000"
.PP
energy policy tag 
.PP
.SS "#define SUB4_ENERGY_POLICY   0x00004000"
.PP
energy policy 
.PP
.SS "#define SUB4_ORPHAN_TERM_NO_WAIT   0x00008000"
.PP
no orphan termination grace period for job 
.PP
.SS "#define SUB4_HOST_FILE   0x00010000"
.PP
user allocation file 
.PP
.SS "#define SUB4_MEM_SWAP_HOST_LIMIT   0x00020000"
.PP
per-job per-host memory/swap limit 
.PP
.SS "#define SUB4_SUBMISSION_ENV_VARS   0x00040000"
.PP
Job submission environment variables. 
.PP
.SS "#define SUB4_AC_MIGRATABLE   0x00080000"
.PP
DC job migratable (by host defragmentation). 
.PP
.SS "#define SUB4_AC_NOT_MIGRATABLE   0x00100000"
.PP
DC job not migratable (by host defragmentation). 
.PP
.SS "#define SUB4_DATA_STAGING_REQ   0x00200000"
.PP
data caching requirement 
.PP
.SS "#define SUB4_DATA_TRANSFER_JOB   0x00400000"
.PP
data tranfer job 
.PP
.SS "#define SUB4_DATA_USER_GROUP   0x00800000"
.PP
group to use when cache permisssions is set to group 
.PP
.SS "#define SUB4_COLLECT_ENERGY_RELATED_USAGE   0x01000000"
.PP
collect energy related usage 
.PP
.SS "#define SUB4_PEND_TIME_LIMIT   0x02000000"
.PP
pending time limit requirement 
.PP
.SS "#define SUB4_ELIGIBLE_PEND_TIME_LIMIT   0x04000000"
.PP
eligible pending time limit requirement 
.PP
.SS "#define SUB4_WITHOUT_CMD   0x08000000"
.PP
WorkItem 139257 - Job is submitted without specifying command. 
.PP
.SS "#define SUB4_GPU_REQ   0x10000000"
.PP
GPU requirement. 
.PP
.SS "#define SUB4_GROUP_TRANSF_REQ   0x20000000"
.PP
The secondary Unix group information for job execution. 
.PP
.SS "#define SUB4_STAGE   0x40000000"
.PP
data stage requirement 
.PP
.SS "#define SUB4_PLAN   0x80000000"
.PP
bjobs -plan specified 
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
