.TH "lsb_closependingreasons" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lsb_closependingreasons \- lsb_closependingreasons 
Close an lsb_pendingreasons file.
.PP
\fBlsb_closependingreasons\fP closes the pendingreasonsFile.
.PP
This API function is inside liblsbstream.so.
.PP
\fB#include <lsf/lsbatch.h>\fP
.PP
\fB int lsb_closependingreasons(const char *config)\fP
.PP
.SH "Parameters:"
\fI*\fP config Pointer to the handle of the pendingreasons file.
.PP
.SH "Data Structures:" 
.PP
none
.PP
.SH "Define Statements:" 
.PP
none
.PP
.SH "Returns:"
int:0 
.br
 The function was successful. 
.PP
int:-1 
.br
 The function failed.
.PP
.SH "Errors:" 
.PP
If the function fails, lsberrno is set to indicate the error.
.PP
.SH "Equivalent line commands:" 
.PP
none
.PP
.SH "Files:" 
.PP
$LSB_CONFDIR/cluster_name/configdir/lsb.params
.PP
.SH "See also:"
\fBlsb_openpendingreasons\fP 
.PP
\fBlsb_readstreamline\fP 
.PP
\fBlsb_writependingreasons\fP 
.PP
\fBlsb_readpendingreasons\fP 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
