.TH "lsb_guaranteedResourcePoolInfo" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lsb_guaranteedResourcePoolInfo \- lsb_guaranteedResourcePoolInfo 
Returns information about guaranteed resource pools.
.PP
\fBlsb_guaranteedResourcePoolInfo\fP gets information about guaranteed resource pools. See lsb.resources for more information about parameters.
.PP
\fB#include <lsf/lsbatch.h>\fP
.PP
\fBint lsb_guaranteedResourcePoolInfo(guaranteedResourcePoolInfoReq *request, guaranteedResourcePoolEnt **entries, int *nEntries)\fP
.PP
.SH "Parameters:"
\fI*request\fP Used to describe resource pools of interest. 
.br
\fI**entries\fP Used to pass back information about request guaranteed resource pools. 
.br
\fI*nEntries\fP The number of entries returned via entries.
.PP
.SH "Data Structures:" 
.PP
guaranteedResourcePoolInfoReq guaranteedResourcePoolEnt
.PP
.SH "Returns:"
int:0 
.br
 The function succeeded. 
.PP
int:-1 
.br
 The function failed.
.PP
.SH "Errors:" 
.PP
If the function fails, lsberrno is set to indicate the error.
.PP
.SH "Equivalent line command:" 
.PP
bresoures
.PP
.SH "Files:" 
.PP
${LSB_CONFDIR/cluster_name/configdir/lsb.resources 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
