.TH "lsb_attrReq" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lsb_attrReq \- lsb_attrReq 
Create or delete attributes on specific hosts.
.PP
\fB#include <lsf/lsbatch.h>\fP
.PP
\fB int lsb_attrReq(attrInfoReq_t *req, char **errReply)\fP
.PP
.SH "Parameters:"
\fI*req\fP input, the request that specifies the attribute creation or deletion information 
.br
\fI**errReply\fP output, the error messages from mbatchd
.PP
.SH "Data Structures:" 
.PP
\fB_attrInfoReq\fP
.PP
.SH "Define Statements:" 
.PP
\fBattrAction_t\fP
.PP
.SH "Returns:"
int: 0 
.br
 Function was successful. 
.br
 lsberrno is LSBE_NO_ERROR.
.PP
int: -1 
.br
 Function failed. The request was rejected. 
.br
 A detailed error message in the reply gives failure reasons.
.PP
.SH "Note:"
The caller must free up errReply regardless of whether the return value is 0 or -1.
.PP
.SH "Errors:" 
.PP
If the request fails, lsberrno is set to indicate the error and the reply gives the detailed error messages.
.PP
.SH "Equivalent line command:" 
.PP
battr create 
.br
 battr delete
.PP
\fBFiles\fP 
.PP
$LSB_CONFDIR/cluster_name/configdir/lsb.params
.PP
.SH "See also:"
none 
.PP

.ad l
.nh
.SH NAME
_attrInfoReq \- Attribute request information.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "attrAction_t \fBaction\fP"
.br
.ti -1c
.RI "int \fBattrNum\fP"
.br
.ti -1c
.RI "char ** \fBattrs\fP"
.br
.ti -1c
.RI "int \fBhostNum\fP"
.br
.ti -1c
.RI "char ** \fBhosts\fP"
.br
.ti -1c
.RI "char * \fBuser\fP"
.br
.ti -1c
.RI "char * \fBdesc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Attribute request information. 
.SH "Field Documentation"
.PP 
.SS "attrAction_t \fB_attrInfoReq::action\fP"
.PP
Action: create, delete, or show. 
.PP
.SS "int \fB_attrInfoReq::attrNum\fP"
.PP
The number of requested attributes. 
.PP
.SS "char** \fB_attrInfoReq::attrs\fP"
.PP
The attribute name array. 
.PP
.SS "int \fB_attrInfoReq::hostNum\fP"
.PP
The number of hosts in the request. 
.PP
.SS "char** \fB_attrInfoReq::hosts\fP"
.PP
The host name array. 
.PP
.SS "char* \fB_attrInfoReq::user\fP"
.PP
The user name in the request, only valid for the show action. 
.PP
.SS "char* \fB_attrInfoReq::desc\fP"
.PP
The description of the attribute. 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
