.TH "lsb_deljgrp_ext" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lsb_deljgrp_ext \- lsb_deljgrp_ext 
Deletes the job group.
.PP
\fBlsb_deljgrp_ext\fP deletes the job group.
.PP
\fB#include <lsf/lsbatch.h>\fP
.PP
\fB int lsb_deljgrp_ext(struct jgrpCtrl *cnt, struct jgrpReply **jgrpReplyPtr)\fP
.PP
.SH "Parameters:"
\fIjgrpCtrl\fP *cnt The request of bgdel command 
.br
\fIjgrpReply\fP *jgrpReplyPtr The pointer to the job group reply structure.
.PP
.SH "Data Structures:" 
.PP
jgrpCtrl jgrpReply
.PP
.SH "Define Statements:" none
.PP
.SH "Returns:"
int:0 
.br
 Function was successful. 
.PP
int:<>0 
.br
 Function failed.
.PP
.SH "Errors:" 
.PP
If the function fails, lsberrno and jgrpReplyPtr-> will be set to indicate the error.
.PP
.SH "Equivalent line commands:" 
.PP
none
.PP
.SH "Files:" 
.PP
${LSF_ENVDIR:-/etc}/lsf.conf
.PP
.SH "See also:"
none 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
