.TH "lsb_freeGuaranteedResourcePoolEntArray" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lsb_freeGuaranteedResourcePoolEntArray \- lsb_freeGuaranteedResourcePoolEntArray 
Used to free the memory used by an array of type guaranteedResourcePoolEnt.
.PP
\fB#include <lsf/lsbatch.h>\fP
.PP
\fB void lsb_freeGuaranteedResourcePoolEntArray(guaranteedResourcePoolEnt *ent, int nEnt)\fP
.PP
.SH "Data Structures:" 
.PP
guaranteedResourcePoolEnt
.PP
.SH "Returns:"
void 
.br
 This function has no return value.
.PP
.SH "Errors:" 
.PP
None.
.PP
.SH "Equivalent line command:" 
.PP
None.
.PP
.SH "Files:" 
.PP
None. 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
