.TH "lsb_serviceClassInfo" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lsb_serviceClassInfo \- lsb_serviceClassInfo 
This API accesses the SLA inside mbatchd.
.PP
This API does not accept input and will output all service classes in LSF. The XDR code for this API is client only. Unlike previous versions of LSF, mbatchd now directly encodes parts of its own data structures into the stream and does not use a library data structure. \fB#include <lsf/lsbatch.h>\fP
.PP
\fB struct serviceClass * lsb_serviceClassInfo(int *n)\fP
.PP
.SH "Parameters:"
\fIn\fP The number of groups.
.PP
.SH "Data Structures:" 
.PP
serviceClass
.PP
.SH "Define Statements:" none
.PP
.SH "Returns:"
struct serviceClass * 
.br
 Function was successful. 
.PP
NULL Function failed.
.PP
.SH "Errors:" 
.PP
If the function fails, lsberrno will be set to indicate the error.
.PP
.SH "Equivalent line commands:" bsla
.PP
.SH "Files:" 
.PP
${LSF_ENVDIR:-/etc}/lsf.conf
.PP
.SH "See also:"
none 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
