.TH "lsb_wait" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lsb_wait \- lsb_wait 
Waits for the job query condition to be satisfied.
.PP
\fB#include <lsf/lsbatch.h>\fP
.PP
\fB int lsb_wait(char *condition, int timeout, int rereg, struct waitReply *wReply);\fP
.PP
.SH "Parameters:"
\fIcondition\fP The wait condition to be satisfied. This expression follows the same format as the job dependency expression for the bsub -w option. 
.br
\fItimeout\fP The timeout interval for the wait condition. This is an integer between 1 and 525600 in minutes. 
.br
\fIrereg\fP The time interval to re-register the wait condition from bwait to mbatchd. This is an integer between 1 and 525600 in minutes. 
.br
\fIwReply\fP Saves the wait condition status back from mbatchd.
.PP
.SH "Returns:"
0: Function is successful, and triggers the wait condition. 
.PP
-1: Function failed.
.PP
.SH "Errors:" 
.PP
If the function fails, lsberrno is set to indicate the error.
.PP
.SH "Equivalent line commands:" 
.PP
bwait 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
