.TH "lsb_addjgrp" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lsb_addjgrp \- lsb_addjgrp 
Adds a job group.
.PP
\fBlsb_addjgrp\fP adds a job group.
.PP
\fB#include <lsf/lsbatch.h>\fP
.PP
\fB int lsb_addjgrp(struct jgrpAdd *jgrpAddPtr, struct jgrpReply **jgrpReplyPtr)\fP
.PP
.SH "Parameters:"
\fIjgrpAdd\fP *jgrpAddPtr The pointer to the job group add structure. 
.br
\fIjgrpReply\fP *jgrpReplyPtr The pointer to the job group reply structure.
.PP
.SH "Data Structures:" 
.PP
jgrpAdd jgrpReply
.PP
.SH "Define Statements:" none
.PP
.SH "Returns:"
int:0 
.br
 Function was successful. 
.PP
int:-1 
.br
 Function failed.
.PP
.SH "Errors:" 
.PP
If the function fails, lsberrno and jgrpReplyPtr-> will be set to indicate the error.
.PP
.SH "Equivalent line commands:" 
.PP
bgadd
.PP
.SH "Files:" 
.PP
${LSF_ENVDIR:-/etc}/lsf.conf
.PP
.SH "See also:"
none 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
