.TH "lsb_rc_showstatus" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lsb_rc_showstatus \- lsb_rc_showstatus 
Displays each host provider information from the resource connector plugin
.PP
\fB#include <lsf/lsbatch.h>\fP
.PP
\fB void lsb_rc_showstatus(struct rcProviderStatusReq* req, struct rcProviderStatusRep* rep)\fP
.PP
.SH "Parameters:"
\fI*req\fP Request options for rc show status
.PP
.SH "Data Structures:" 
.PP
rcProviderStatusReq rcProviderStatusRep
.PP
.SH "Returns:"
void
.PP
.SH "Errors:" 
.PP
Check lsberrno to determine if the function has completed successfully.
.PP
.SH "Files:" 
.PP
N/A 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
