.TH "RsrcReqHandler_NewFn" 3 "10 Jun 2021" "Version 10.1" "IBM Spectrum LSF 10.1 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RsrcReqHandler_NewFn \- RsrcReqHandler_NewFn 
Signature for functions that handle newly submitted resource requirement.
.PP
Use these functions for newly submitted jobs to
.IP "\(bu" 2
get the user-specified resource requirement messages
.IP "\(bu" 2
attach handler-specific data to peer jobs.
.PP
.PP
\fB#include <lssched.h>\fP
.PP
\fB typedef int (* RsrcReqHandler_NewFn) (INT_RsrcReq *resreq)\fP
.PP
.SH "Parameters:"
\fIresreq\fP [IN] : Resource requirement object for newly submitted job. This is an internal object representing resource requirements for peer jobs.
.PP
.SH "Returns:"
int:0  successfully processed newly submitted resource requirements. 
.PP
int:<0  failed to process.
.PP
.SH "See also:"
\fBRsrcReqHandlerType\fP 
.PP
\fBRsrcReqHandler_FreeFn\fP 
.PP
\fBextsched_resreq_registerhandler\fP 
.PP
\fBextsched_resreq_getextresreq\fP 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IBM Spectrum LSF 10.1 C API Reference from the source code.
