
.ad l

.TH bladmin 8 "July 2021" "" ""
.ll 72

.ce 1000
\fBbladmin\fR
.ce 0

.sp 2
Administrative tool for IBM Spectrum LSF License Scheduler.
.sp 2

.SH Synopsis

.sp 2
\fBbladmin\fR subcommand
.sp 2
\fBbladmin\fR [\fB-h\fR | \fB-V\fR]
.SH Description

.sp 2
The bladmin command provides a set of subcommands to control LSF
License Scheduler.
.sp 2
You must be root or a LSF License Scheduler administrator to use
this command.
.SH Subcommand synopsis

.sp 2
\fBckconfig\fR
.sp 2
\fBreconfig\fR [host_name ... | \fBall\fR]
.sp 2
\fBshutdown\fR [host_name ... | \fBall\fR]
.sp 2
\fBblddebug\fR [\fB-c\fR class_name ...] [\fB-l\fR debug_level]
[\fB-f\fR logfile_name] [\fB-o\fR]
.sp 2
\fBblcdebug\fR\fB\fR [\fB-l\fR debug_level] [\fB-f\fR
logfile_name] [\fB-o\fR] collector_name ... | all
.sp 2
\fB-h\fR
.sp 2
\fB-V\fR
.SH Usage

.sp 2
\fBckconfig\fR
.br
         Checks LSF License Scheduler configuration in the
         LSF_ENVDIR/lsf.licensescheduler and lsf.conf files.
.sp 2
         By default, the bladmin ckconfig command displays only
         the result of the configuration file check. If warning
         errors are found, the bladmin command prompts you to
         enter the y option to display detailed messages.
.sp 2
\fBreconfig [\fIhost_name\fB ... | all]\fR
.br
         Reconfigures LSF License Scheduler.
.sp 2
\fBshutdown [\fIhost_name\fB ... | all]\fR
.br
         Shuts down LSF License Scheduler.
.sp 2
\fBblddebug [-c \fIclass_name\fB ...] [-l \fIdebug_level\fB] [-f
\fIlogfile_name\fB] [-o]\fR
.br
         Sets the message log level for the bld daemon to include
         extra information in log files. You must be root or the
         LSF administrator to use this command.
.sp 2
         If the bladmin blddebug command is used without any
         options, the following default values are used:
.sp 2
         \fB\fR\fIclass_name\fR=0\fB\fR
.br
                  No additional classes are logged.
.sp 2
         \fB\fR\fIdebug_level\fR=0\fB\fR
.br
                  \fRLOG_DEBUG\fR level in the \fBLS_LOG_MASK\fR
                  parameter.
.sp 2
         \fB\fR\fIlogfile_name\fR=\fIdaemon_name\fR.log.\fIhost_name\fR\fB\fR
.br
                  Current LSF system log file in the LSF system
                  log file directory.
.sp 2
         \fB-c \fIclass_name\fB ...\fR
.br
                  Specifies software classes for which debug
                  messages are to be logged.
.sp 2
                  Format of \fIclass_name\fR is the name of a
                  class, or a list of class names separated by
                  spaces and enclosed in quotation marks. Classes
                  are also listed in the \fRlsf.h\fR file.
.sp 2
                  The following log classes are supported:
.sp 2
                  \fB\fRLC_AUTH\fB\fR
.br
                           Log authentication messages.
.sp 2
                  \fB\fRLC_COMM\fB\fR
.br
                           Log communication messages.
.sp 2
                  \fB\fRLC_FLEX\fB\fR
.br
                           Log everything that is related to
                           \fRFLEX_STAT\fR or \fRFLEX_EXEC\fR
                           Flexera APIs.
.sp 2
                  \fB\fRLC_LICENCE\fB\fR
.br
                           Log license management messages.
.sp 2
                  \fB\fRLC_PREEMPT\fB\fR
.br
                           Log preemption policy messages.
.sp 2
                  \fB\fRLC_RESREQ\fB\fR
.br
                           Log resource requirement messages.
.sp 2
                  \fB\fRLC_TRACE\fB\fR
.br
                           Log significant program walk steps.
.sp 2
                  \fB\fRLC_XDR\fB\fR
.br
                           Log everything that is transferred by
                           XDR.
.sp 2
                  The default debug level is \fR0\fR (no
                  additional classes are logged).
.sp 2
         \fB-l \fIdebug_level\fB\fR
.br
                  Specifies level of detail in debug messages.
                  The higher the number, the more detail that is
                  logged. Higher levels include all lower logging
                  levels. For example, \fRLOG_DEBUG3\fR includes
                  \fRLOG_DEBUG2\fR \fRLOG_DEBUG1\fR, and
                  \fRLOG_DEBUG\fR levels.
.sp 2
                  The following values are supported:
.sp 2
                  \fB\fR0\fB\fR
.br
                           \fRLOG_DEBUG\fR level in parameter
                           \fBLS_LOG_MASK\fR in the lsf.conf
                           file. This is the default value.
.sp 2
                  \fB\fR1\fB\fR
.br
                           \fRLOG_DEBUG1\fR level for extended
                           logging.
.sp 2
                  \fB\fR2 \fB\fR
.br
                           \fRLOG_DEBUG2\fR level for extended
                           logging.
.sp 2
                  \fB\fR3 \fB\fR
.br
                           \fRLOG_DEBUG3\fR level for extended
                           logging.
.sp 2
         \fB-f \fIlogfile_name\fB\fR
.br
                  Specifies the name of the file where debugging
                  messages are logged. The file name can be a
                  full path. If a file name without a path is
                  specified, the file is saved in the LSF system
                  log directory.
.sp 2
                  The name of the file has the following format:
.sp 2
                  \fR\fIlogfile_name.daemon_name.\fRlog\fI.host_name\fR\fR
.sp 2
                  On UNIX, if the specified path is not valid,
                  the log file is created in the /tmp directory.
.sp 2
                  On Windows, if the specified path is not valid,
                  no log file is created.
.sp 2
                  The default is the current LSF system log file
                  in the LSF system log file directory.
.sp 2
         \fB-o\fR
.br
                  Turns off temporary debug settings and resets
                  them to the daemon starting state. The message
                  log level is reset back to the value of
                  \fRLS_LOG_MASK\fR and classes are reset to the
                  value of \fRLSB_DEBUG_BLD\fR. The log file is
                  also reset to the default log file.
.sp 2
\fBblcdebug [-l \fIdebug_level\fB] [-f \fIlogfile_name\fB] [-o]
\fIcollector_name\fB | all\fR
.br
         Sets the message log level for the blcollect command to
         include additional information in log files. You must be
         root or the LSF administrator to use this command.
.sp 2
         If the bladmin blcdebug command is used without any
         options, the following default values are used:
.sp 2
         \fB\fR\fIdebug_level\fR=0\fB\fR
.br
                  The \fRLOG_DEBUG\fR level in the
                  \fBLS_LOG_MASK\fR parameter.
.sp 2
         \fB\fR\fIlogfile_name\fR=\fIdaemon_name\fR.log.\fIhost_name\fR\fB\fR
.br
                  Current LSF system log file in the LSF system
                  log file directory.
.sp 2
         \fB\fR\fIcollector_name\fR=default\fB\fR
.br
                  The default collector name.
.sp 2
         \fB-l \fIdebug_level\fB\fR
.br
                  Specifies level of detail in debug messages.
                  The higher the number, the more detail that is
                  logged. Higher levels include all lower logging
                  levels. For example, \fRLOG_DEBUG3\fR includes
                  \fRLOG_DEBUG2\fR \fRLOG_DEBUG1\fR, and
                  \fRLOG_DEBUG\fR levels.
.sp 2
                  The following values are supported:
.sp 2
                  \fB\fR0\fB\fR
.br
                           \fRLOG_DEBUG\fR level in parameter
                           \fBLS_LOG_MASK\fR in the lsf.conf
                           file. This is the default value.
.sp 2
                  \fB\fR1\fB\fR
.br
                           \fRLOG_DEBUG1\fR level for extended
                           logging.
.sp 2
                  \fB\fR2 \fB\fR
.br
                           \fRLOG_DEBUG2\fR level for extended
                           logging.
.sp 2
                  \fB\fR3 \fB\fR
.br
                           \fRLOG_DEBUG3\fR level for extended
                           logging.
.sp 2
         \fB-f \fIlogfile_name\fB\fR
.br
                  Specifies the name of the file where debugging
                  messages are logged. The file name can be a
                  full path. If a file name without a path is
                  specified, the file is saved in the LSF system
                  log directory.
.sp 2
                  The name of the file has the following format:
.sp 2
                  \fR\fIlogfile_name.daemon_name.\fRlog\fI.host_name\fR\fR
.sp 2
                  On UNIX, if the specified path is not valid,
                  the log file is created in the /tmp directory.
.sp 2
                  On Windows, if the specified path is not valid,
                  no log file is created.
.sp 2
                  The default is the current LSF system log file
                  in the LSF system log file directory.
.sp 2
         \fB-o\fR
.br
                  Turns off temporary debug settings and resets
                  them to the daemon starting state. The message
                  log level is reset back to the value of
                  \fRLS_LOG_MASK\fR and classes are reset to the
                  value of \fRLSB_DEBUG_BLD\fR. The log file is
                  also reset to the default log file.
.sp 2
                  If a collector name is not specified, default
                  value is to restore the original log mask and
                  log file directory for the \fRdefault\fR
                  collector.
.sp 2
         \fB\fIcollector_name\fB ... | all\fR
.br
                  Specifies the collector names, separated by
                  blanks. The \fRall\fR keyword means all the
                  collectors.
.sp 2
\fB-h\fR
.br
         Prints command usage to stderr and exits.
.sp 2
\fB-V\fR
.br
         Prints release version to stderr and exits.
.SH See also

.sp 2
blhosts, lsf.licensescheduler, lsf.conf