.ds ]W %
.ds ]L
.hy 0
.nh
.na
.TH egoremoverc 8 "Mar 2014   EGO 3.4.0"
.br

.SH NAME
\fBegoremoverc\fR - Prevents automatic startup of EGO on a UNIX host.

.SH Synopsis
.BR
.PP
 egoremoverc.sh 
.SH Description
.BR
.PP

.PP
Prevents automatic startup of EGO on a UNIX host when a system reboot 
command is issued. After this script/command is issued, EGO no longer 
starts automatically if the host gets rebooted. In such a case, you must manually 
start EGO after the host has started up.

.PP
Removes the EGO links created in the system startup directory by 
egosetrc.

.PP
This is an administrative command. You must be logged on as root to issue this 
command.

