.ds ]W %
.ds ]L
.hy 0
.nh
.na
.TH egostartup 8 "Mar 2014   EGO 3.4.0"
.br

.SH NAME
\fBegostartup\fR - Starts all components of a EGO cluster.

.SH Synopsis
.BR
.PP
 egostartup.sh  egostartup.bat 
.SH Description
.BR
.PP

.PP
Starts EGO components in a EGO cluster.

.PP
This is an administrative command. On UNIX, you must also be logged on with 
root permissions to issue this command; on Windows, you must be logged on as 
the OS account administrator, egoadmin.

.PP
You cannot issue this command from a compute host unless the master host is up 
and running. To use this command on UNIX, you must have root permission on 
each host and have rsh configured for your account. You may need to add an entry 
for the local host in the .rhosts file for root.

.PP
You cannot start EGO on UNIX hosts from a Windows host, or vice versa.

