
.ad l

.TH fodadmin 8 "June 2016" "" ""n.ll 72

.ce 1000
\fBfodadmin\fR
.ce 0

.sp 2
Starts applications under FOD or shuts down FOD.
.sp 2

.SH Synopsis

.sp 2
\fBfodadmin shutdown\fR [host_name... | all] \fBfodadmin\fR [-h |
-V]
.sp 2
You must be License Scheduler administrator to use this command.
.sp 2
This command starts applications under FOD or shuts down FOD.
.sp 2
By default, shuts down FOD on the local host.
.SH Options

.sp 2
\fBshutdown [\fIhost_name\fB... | all]\fR
.br
         Shuts down FOD on the specified hosts. This may shut
         down applications on the hosts that are managed by FOD.
         If you shut down the master host, FOD starts up on
         another host, if possible. Specify all to shut down FOD
         for the cluster.
.sp 2
\fB-h\fR
.br
         Prints command usage to stderr and exits.
.sp 2
\fB-V\fR
.br
         Prints FOD release version to stderr and exits.
.sp 2
