---
name: 'Build and Push Container Images'
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  latest:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Repo
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and Push images
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          tags: ghcr.io/washu-it-ris/base-openmpi:latest
          platforms: linux/amd64
          labels: |
            org.opencontainers.image.title=RIS Base OpenMPI
            org.opencontainers.image.description=RIS Managed OpenMPI Base Container for use with LSF 10.1 Compute1
            org.opencontainers.image.vendor=ris.wustl.edu
            org.opencontainers.image.url=https://docs.hidden.io
            org.opencontainers.image.source=https://github.com/WashU-IT-RIS/demo-openmpi

  ubuntu20_mofed5-8_openmpi4-1:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Repo
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and Push images
        uses: docker/build-push-action@v6
        with:
          file: Dockerfiles/ubuntu20-mofed5.8-openmpi4.1
          tags: ghcr.io/washu-it-ris/base-openmpi:ubuntu20-mofed5.8-openmpi4.1
          platforms: linux/amd64

  ubuntu22_mofed5-8_openmpi4-1:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Repo
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and Push images
        uses: docker/build-push-action@v6
        with:
          file: Dockerfiles/ubuntu20-mofed5.8-openmpi4.1
          tags: ghcr.io/washu-it-ris/base-openmpi:ubuntu22-mofed5.8-openmpi4.1
          platforms: linux/amd64
          labels: |
            org.opencontainers.image.title=RIS Base OpenMPI
            org.opencontainers.image.description=RIS Managed OpenMPI Base Container for use with LSF 10.1 Compute1
            org.opencontainers.image.vendor=ris.wustl.edu
            org.opencontainers.image.url=https://docs.hidden.io
            org.opencontainers.image.source=https://github.com/WashU-IT-RIS/demo-openmpi

